// Generated by the Spiral compiler (TypeScript backend). Run: node --experimental-strip-types main.ts, or bun main.ts.
function spiral_array_index<T>(array: T[], index: number): T {
    if (!(index >= 0 && index < array.length)) throw new RangeError("array index " + index + " out of bounds for length " + array.length);
    return array[index];
}
function spiral_array_set<T>(array: T[], index: number, value: T): void {
    if (!(index >= 0 && index < array.length)) throw new RangeError("array index " + index + " out of bounds for length " + array.length);
    array[index] = value;
}
type Mut0 = { l0: number };
type Mut1 = { l0: number, l1: number, l2: number };
type Mut2 = { l0: number };
type Mut3 = { l0: number };
function method0(v0: Mut0): boolean {
    let v1: number = v0.l0;
    let v2: boolean = v1 < 7040;
    return v2;
}
function method1(v0: Mut0): boolean {
    let v1: number = v0.l0;
    let v2: boolean = v1 < 60;
    return v2;
}
function method4(v0: number, v1: Mut3): boolean {
    let v2: number = v1.l0;
    let v3: boolean = v2 < v0;
    return v3;
}
function method5(v0: number, v1: Mut3): boolean {
    let v2: number = v1.l0;
    let v3: boolean = v2 < v0;
    return v3;
}
function method6(v0: Array<number>, v1: Array<number>, v2: number, v3: number, v4: number, v5: number, v6: number, v7: number, v8: number, v9: number): void {
    let v10: number = Math.sin(v2);
    let v11: number = v7 * v10;
    let v12: number = Math.sin(v3);
    let v13: number = v11 * v12;
    let v14: number = Math.cos(v4);
    let v15: number = v13 * v14;
    let v16: number = Math.cos(v2);
    let v17: number = v8 * v16;
    let v18: number = v17 * v12;
    let v19: number = v18 * v14;
    let v20: number = v15 - v19;
    let v21: number = v7 * v16;
    let v22: number = Math.sin(v4);
    let v23: number = v21 * v22;
    let v24: number = v20 + v23;
    let v25: number = v8 * v10;
    let v26: number = v25 * v22;
    let v27: number = v24 + v26;
    let v28: number = Math.cos(v3);
    let v29: number = v6 * v28;
    let v30: number = v29 * v14;
    let v31: number = v27 + v30;
    let v32: number = v21 * v14;
    let v33: number = v25 * v14;
    let v34: number = v32 + v33;
    let v35: number = v13 * v22;
    let v36: number = v34 - v35;
    let v37: number = v18 * v22;
    let v38: number = v36 + v37;
    let v39: number = v29 * v22;
    let v40: number = v38 - v39;
    let v41: number = v17 * v28;
    let v42: number = v11 * v28;
    let v43: number = v41 - v42;
    let v44: number = v6 * v12;
    let v45: number = v43 + v44;
    let v46: number = v45 + 100;
    let v47: number = 1 / v46;
    let v48: number = 80 + v5;
    let v49: number = 40 * v47;
    let v50: number = v49 * v31;
    let v51: number = v50 * 2;
    let v52: number = v48 + v51;
    let v53: number = (v52) | 0;
    let v54: number = v49 * v40;
    let v55: number = 22 + v54;
    let v56: number = (v55) | 0;
    let v57: number = Math.imul(v56, 160);
    let v58: number = (v53 + v57) | 0;
    let v59: boolean = v58 >= 0;
    let v61: boolean;
    if (v59) {
        let v60: boolean = v58 < 7040;
        v61 = v60;
    } else {
        v61 = false;
    }
    if (v61) {
        let v62: number = spiral_array_index(v0, v58);
        let v63: boolean = v47 > v62;
        if (v63) {
            spiral_array_set(v0, v58, v47);
            spiral_array_set(v1, v58, v9);
        }
    }
}
function method3(v0: Array<number>, v1: Array<number>, v2: number, v3: number, v4: number, v5: number, v6: number): void {
    let v7: number = -v5;
    let v8: Mut3 = { l0: v7 };
    while (method4(v5, v8)) {
        let v10: Mut3 = { l0: v7 };
        while (method5(v5, v10)) {
            let v12: number = v8.l0;
            let v13: number = v10.l0;
            let v14: number = 59;
            method6(v0, v1, v2, v3, v4, v6, v12, v13, v7, v14);
            let v15: number = 92;
            method6(v0, v1, v2, v3, v4, v6, v5, v13, v12, v15);
            let v16: number = -v12;
            let v17: number = 47;
            method6(v0, v1, v2, v3, v4, v6, v7, v13, v16, v17);
            let v18: number = 61;
            method6(v0, v1, v2, v3, v4, v6, v16, v13, v5, v18);
            let v19: number = -v13;
            let v20: number = 62;
            method6(v0, v1, v2, v3, v4, v6, v12, v7, v19, v20);
            let v21: number = 60;
            method6(v0, v1, v2, v3, v4, v6, v12, v5, v13, v21);
            let v22: number = v10.l0;
            let v23: number = v22 + 0.6;
            v10.l0 = v23;
        }
        let v24: number = v8.l0;
        let v25: number = v24 + 0.6;
        v8.l0 = v25;
    }
}
function method7(v0: Mut0): boolean {
    let v1: number = v0.l0;
    let v2: boolean = v1 < 44;
    return v2;
}
function method8(v0: Mut0): boolean {
    let v1: number = v0.l0;
    let v2: boolean = v1 < 160;
    return v2;
}
function method2(v0: Array<number>, v1: Array<number>, v2: number, v3: number, v4: number, v5: number): number {
    let v6: Mut0 = { l0: 0 };
    while (method0(v6)) {
        let v8: number = v6.l0;
        spiral_array_set(v0, v8, 0);
        spiral_array_set(v1, v8, 46);
        let v9: number = (v8 + 1) | 0;
        v6.l0 = v9;
    }
    let v10: number = 20;
    let v11: number = (-40);
    method3(v0, v1, v2, v3, v4, v10, v11);
    let v12: number = 10;
    let v13: number = 10;
    method3(v0, v1, v2, v3, v4, v12, v13);
    let v14: number = 5;
    let v15: number = 40;
    method3(v0, v1, v2, v3, v4, v14, v15);
    process.stdout.write("u001b[H");
    let v16: Mut2 = { l0: v5 };
    let v17: Mut0 = { l0: 0 };
    while (method7(v17)) {
        let v19: number = v17.l0;
        let v20: Mut0 = { l0: 0 };
        while (method8(v20)) {
            let v22: number = v20.l0;
            let v23: number = Math.imul(v19, 160);
            let v24: number = (v22 + v23) | 0;
            let v25: number = spiral_array_index(v1, v24);
            let v26: boolean = v25 === 59;
            let v44: string;
            if (v26) {
                let v27: string = ";";
                v44 = v27;
            } else {
                let v28: boolean = v25 === 92;
                if (v28) {
                    let v29: string = "\\";
                    v44 = v29;
                } else {
                    let v30: boolean = v25 === 47;
                    if (v30) {
                        let v31: string = "/";
                        v44 = v31;
                    } else {
                        let v32: boolean = v25 === 61;
                        if (v32) {
                            let v33: string = "=";
                            v44 = v33;
                        } else {
                            let v34: boolean = v25 === 62;
                            if (v34) {
                                let v35: string = ">";
                                v44 = v35;
                            } else {
                                let v36: boolean = v25 === 60;
                                if (v36) {
                                    let v37: string = "<";
                                    v44 = v37;
                                } else {
                                    let v38: string = ".";
                                    v44 = v38;
                                }
                            }
                        }
                    }
                }
            }
            process.stdout.write(v44);
            let v45: number = v16.l0;
            let v46: number = Math.imul(v45, 31);
            let v47: number = (v46 + v25) | 0;
            let v48: number = (v47 % 1000003) | 0;
            v16.l0 = v48;
            let v49: number = (v22 + 1) | 0;
            v20.l0 = v49;
        }
        process.stdout.write("\n");
        let v50: number = (v19 + 1) | 0;
        v17.l0 = v50;
    }
    let v51: number = v16.l0;
    return v51;
}
export function main(): number {
    let v0: Array<number> = new Array<number>(7040).fill(0);
    let v1: Mut0 = { l0: 0 };
    while (method0(v1)) {
        let v3: number = v1.l0;
        spiral_array_set(v0, v3, 0);
        let v4: number = (v3 + 1) | 0;
        v1.l0 = v4;
    }
    let v5: Array<number> = new Array<number>(7040).fill(0);
    let v6: Mut0 = { l0: 0 };
    while (method0(v6)) {
        let v8: number = v6.l0;
        spiral_array_set(v5, v8, 46);
        let v9: number = (v8 + 1) | 0;
        v6.l0 = v9;
    }
    let v10: Mut1 = { l0: 0, l1: 0, l2: 0 };
    let v11: Mut2 = { l0: 0 };
    let v12: Mut0 = { l0: 0 };
    while (method1(v12)) {
        let v14: number = v12.l0;
        let v15: number = v10.l0;
        let v16: number = v10.l1;
        let v17: number = v10.l2;
        let v18: number = v11.l0;
        let v19: number = method2(v0, v5, v15, v16, v17, v18);
        v11.l0 = v19;
        let v20: number = v10.l0;
        let v21: number = v10.l1;
        let v22: number = v10.l2;
        let v23: number = v20 + 0.05;
        let v24: number = v21 + 0.05;
        let v25: number = v22 + 0.01;
        v10.l0 = v23;
        v10.l1 = v24;
        v10.l2 = v25;
        let v26: number = (v14 + 1) | 0;
        v12.l0 = v26;
    }
    let v27: number = v11.l0;
    process.stdout.write("cube: " + String(60) + " frames, checksum " + String(v27) + "\n");
    return 0;
}
process.exitCode = main();
