name: gh-pages
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    timeout-minutes: 240
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v4

      - uses: moonrepo/setup-rust@v1
        with:
          channel: 'nightly-2024-07-14'
          components: 'clippy,rust-src,rustfmt'
          targets: 'wasm32-unknown-unknown'

      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.100-preview.1.24101.2'
          cache: true
          cache-dependency-path: paket.lock

      - uses: actions/setup-node@v3
        with:
          node-version: 21

      - uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - uses: snok/install-poetry@v1
        with:
          virtualenvs-create: true
          virtualenvs-in-project: true
          installer-parallel: true

      - run: pwsh scripts/init.ps1

      - run: pwsh scripts/build.ps1

      - run: pwsh scripts/publish.ps1

      - run: pwsh dist/scripts/publish-bin.ps1
        env:
            NFTSTORAGE_API_KEY: ${{ secrets.NFTSTORAGE_API_KEY }}

      - uses: actions/upload-artifact@v3
        with:
          name: gh-pages
          path: dist
          retention-days: 30

  push:
    needs: build
    timeout-minutes: 180
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4

      - uses: actions/download-artifact@v3
        with:
          name: gh-pages
          path: gh-pages

      - uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: gh-pages
