// Generated by Spiral portable Rust backend.
#![allow(unused_mut, non_snake_case)]

#![allow(dead_code)]

use std::rc::Rc;

fn SpiralStringIndex(value: &Rc<str>, index: i32) -> u8 {
    assert!(index >= 0, "negative Spiral string index");
    let bytes = value.as_bytes();
    let index = index as usize;
    assert!(index < bytes.len(), "Spiral string index out of bounds");
    bytes[index]
}

fn SpiralStringSlice(value: &Rc<str>, from_index: i32, to_index: i32) -> Rc<str> {
    assert!(from_index >= 0, "negative Spiral string slice start");
    let bytes = value.as_bytes();
    let length = bytes.len() as i32;
    if to_index < from_index { return Rc::<str>::from(""); }
    assert!(from_index <= length, "Spiral string slice start out of bounds");
    assert!(to_index < length, "Spiral string slice end out of bounds");
    let from_index = from_index as usize;
    let to_index = to_index as usize;
    let slice = &bytes[from_index..=to_index];
    Rc::<str>::from(std::str::from_utf8(slice).expect("Spiral string slice must preserve UTF-8 boundaries"))
}

fn SpiralStringConcat(left: &Rc<str>, right: &Rc<str>) -> Rc<str> {
    let mut value = String::with_capacity(left.len() + right.len());
    value.push_str(left);
    value.push_str(right);
    Rc::<str>::from(value.into_boxed_str())
}

type Recursive0 = Rc<Recursive0Node>;
#[derive(Clone)]
enum Recursive0Node {
    Case0,
    Case1 { v0: i32, v1: Rc<str>, v2: Recursive0 },
}

fn RecursiveCreate0_0() -> Recursive0 {
    Rc::new(Recursive0Node::Case0)
}
fn RecursiveCreate0_1(v0: i32, v1: Rc<str>, v2: Recursive0) -> Recursive0 {
    Rc::new(Recursive0Node::Case1 { v0, v1, v2 })
}
fn RecursiveTag0(value: &Recursive0) -> i32 {
    match value.as_ref() {
        Recursive0Node::Case0 => 0,
        Recursive0Node::Case1 { .. } => 1,
    }
}
fn RecursiveField0_0(value: &Recursive0) -> i32 {
    match value.as_ref() {
        Recursive0Node::Case1 { v0, .. } => *v0,
        _ => panic!("recursive union field 0 requested from wrong case"),
    }
}
fn RecursiveField0_1(value: &Recursive0) -> Rc<str> {
    match value.as_ref() {
        Recursive0Node::Case1 { v1, .. } => v1.clone(),
        _ => panic!("recursive union field 1 requested from wrong case"),
    }
}
fn RecursiveField0_2(value: &Recursive0) -> Recursive0 {
    match value.as_ref() {
        Recursive0Node::Case1 { v2, .. } => v2.clone(),
        _ => panic!("recursive union field 2 requested from wrong case"),
    }
}
fn RecursiveClone0(_value: &Recursive0) {}
fn RecursiveDrop0(_value: &Recursive0) {}

type Recursive1 = Rc<Recursive1Node>;
#[derive(Clone)]
enum Recursive1Node {
    Case0,
    Case1 { v0: Rc<str>, v1: Rc<str>, v2: i64, v3: Recursive1 },
    Case2 { v0: Rc<str>, v1: Rc<str>, v2: Recursive1, v3: Recursive1 },
}

fn RecursiveCreate1_0() -> Recursive1 {
    Rc::new(Recursive1Node::Case0)
}
fn RecursiveCreate1_1(v0: Rc<str>, v1: Rc<str>, v2: i64, v3: Recursive1) -> Recursive1 {
    Rc::new(Recursive1Node::Case1 { v0, v1, v2, v3 })
}
fn RecursiveCreate1_2(v0: Rc<str>, v1: Rc<str>, v2: Recursive1, v3: Recursive1) -> Recursive1 {
    Rc::new(Recursive1Node::Case2 { v0, v1, v2, v3 })
}
fn RecursiveTag1(value: &Recursive1) -> i32 {
    match value.as_ref() {
        Recursive1Node::Case0 => 0,
        Recursive1Node::Case1 { .. } => 1,
        Recursive1Node::Case2 { .. } => 2,
    }
}
fn RecursiveCaseField1_1_0(value: &Recursive1) -> Rc<str> {
    match value.as_ref() {
        Recursive1Node::Case1 { v0, .. } => v0.clone(),
        _ => panic!("recursive union case 1 field 0 requested from wrong case"),
    }
}
fn RecursiveCaseField1_1_1(value: &Recursive1) -> Rc<str> {
    match value.as_ref() {
        Recursive1Node::Case1 { v1, .. } => v1.clone(),
        _ => panic!("recursive union case 1 field 1 requested from wrong case"),
    }
}
fn RecursiveCaseField1_1_2(value: &Recursive1) -> i64 {
    match value.as_ref() {
        Recursive1Node::Case1 { v2, .. } => *v2,
        _ => panic!("recursive union case 1 field 2 requested from wrong case"),
    }
}
fn RecursiveCaseField1_1_3(value: &Recursive1) -> Recursive1 {
    match value.as_ref() {
        Recursive1Node::Case1 { v3, .. } => v3.clone(),
        _ => panic!("recursive union case 1 field 3 requested from wrong case"),
    }
}
fn RecursiveCaseField1_2_0(value: &Recursive1) -> Rc<str> {
    match value.as_ref() {
        Recursive1Node::Case2 { v0, .. } => v0.clone(),
        _ => panic!("recursive union case 2 field 0 requested from wrong case"),
    }
}
fn RecursiveCaseField1_2_1(value: &Recursive1) -> Rc<str> {
    match value.as_ref() {
        Recursive1Node::Case2 { v1, .. } => v1.clone(),
        _ => panic!("recursive union case 2 field 1 requested from wrong case"),
    }
}
fn RecursiveCaseField1_2_2(value: &Recursive1) -> Recursive1 {
    match value.as_ref() {
        Recursive1Node::Case2 { v2, .. } => v2.clone(),
        _ => panic!("recursive union case 2 field 2 requested from wrong case"),
    }
}
fn RecursiveCaseField1_2_3(value: &Recursive1) -> Recursive1 {
    match value.as_ref() {
        Recursive1Node::Case2 { v3, .. } => v3.clone(),
        _ => panic!("recursive union case 2 field 3 requested from wrong case"),
    }
}
fn RecursiveClone1(_value: &Recursive1) {}
fn RecursiveDrop1(_value: &Recursive1) {}

fn show_i640(v0: i64) -> Rc<str> {
    let v1: i64 = v0 % 10;
    let v2: bool = v1 == 0;
    let mut v32: Rc<str>;
    if v2 {
        let v3: Rc<str> = Rc::<str>::from("0");
        v32 = v3;
    } else {
        let v4: bool = v1 == 1;
        if v4 {
            let v5: Rc<str> = Rc::<str>::from("1");
            v32 = v5;
        } else {
            let v6: bool = v1 == 2;
            if v6 {
                let v7: Rc<str> = Rc::<str>::from("2");
                v32 = v7;
            } else {
                let v8: bool = v1 == 3;
                if v8 {
                    let v9: Rc<str> = Rc::<str>::from("3");
                    v32 = v9;
                } else {
                    let v10: bool = v1 == 4;
                    if v10 {
                        let v11: Rc<str> = Rc::<str>::from("4");
                        v32 = v11;
                    } else {
                        let v12: bool = v1 == 5;
                        if v12 {
                            let v13: Rc<str> = Rc::<str>::from("5");
                            v32 = v13;
                        } else {
                            let v14: bool = v1 == 6;
                            if v14 {
                                let v15: Rc<str> = Rc::<str>::from("6");
                                v32 = v15;
                            } else {
                                let v16: bool = v1 == 7;
                                if v16 {
                                    let v17: Rc<str> = Rc::<str>::from("7");
                                    v32 = v17;
                                } else {
                                    let v18: bool = v1 == 8;
                                    if v18 {
                                        let v19: Rc<str> = Rc::<str>::from("8");
                                        v32 = v19;
                                    } else {
                                        let v20: bool = v1 == 9;
                                        if v20 {
                                            let v21: Rc<str> = Rc::<str>::from("9");
                                            v32 = v21;
                                        } else {
                                            let v22: Rc<str> = Rc::<str>::from("0");
                                            v32 = v22;
                                        }
                                    }
                                }
                            }
                        }
                    }
                }
            }
        }
    }
    let v33: i64 = v0 / 10;
    let v34: bool = v33 == 0;
    if v34 {
        return v32;
    } else {
        let v35: Rc<str> = show_i640(v33);
        let v36: Rc<str> = SpiralStringConcat(&v35, &v32);
        return v36;
    }
}

fn times2(v0: Rc<str>, v1: i64) -> Rc<str> {
    let v2: bool = v1 <= 0;
    if v2 {
        let v3: Rc<str> = Rc::<str>::from("");
        return v3;
    } else {
        let v4: i64 = v1 - 1;
        let v5: Rc<str> = times2(v0.clone(), v4);
        let v6: Rc<str> = SpiralStringConcat(&v0, &v5);
        return v6;
    }
}

fn last_sep3(mut v0: Rc<str>, mut v1: i32, mut v2: i32) -> i32 {
    'spiral_tail: loop {
        let v3: i32 = (v0).len() as i32;
        let v4: bool = v1 == v3;
        if v4 {
            return v2;
        } else {
            let v5: u8 = SpiralStringIndex(&v0, v1);
            let v6: bool = v5 == 47;
            let mut v9: i32;
            if v6 {
                v9 = v1;
            } else {
                let v7: bool = v5 == b'\\';
                if v7 {
                    v9 = v1;
                } else {
                    v9 = v2;
                }
            }
            let v10: i32 = v1 + 1;
            let __spiral_tail_arg0: Rc<str> = v0.clone();
            let __spiral_tail_arg1: i32 = v10;
            let __spiral_tail_arg2: i32 = v9;
            v0 = __spiral_tail_arg0;
            v1 = __spiral_tail_arg1;
            v2 = __spiral_tail_arg2;
            continue 'spiral_tail;
        }
    }
}

fn lay1(mut v0: Rc<str>, mut v1: i64) -> i32 {
    'spiral_tail: loop {
        let v2: bool = v1 < 0;
        if v2 {
            return 0;
        } else {
            let v4: i32 = i32::from(std::fs::create_dir_all(v0.as_ref()).is_err());
            let v5: bool = v1 == 0;
            let mut v35: Rc<str>;
            if v5 {
                let v6: Rc<str> = Rc::<str>::from("0");
                v35 = v6;
            } else {
                let v7: bool = v1 == 1;
                if v7 {
                    let v8: Rc<str> = Rc::<str>::from("1");
                    v35 = v8;
                } else {
                    let v9: bool = v1 == 2;
                    if v9 {
                        let v10: Rc<str> = Rc::<str>::from("2");
                        v35 = v10;
                    } else {
                        let v11: bool = v1 == 3;
                        if v11 {
                            let v12: Rc<str> = Rc::<str>::from("3");
                            v35 = v12;
                        } else {
                            let v13: bool = v1 == 4;
                            if v13 {
                                let v14: Rc<str> = Rc::<str>::from("4");
                                v35 = v14;
                            } else {
                                let v15: bool = v1 == 5;
                                if v15 {
                                    let v16: Rc<str> = Rc::<str>::from("5");
                                    v35 = v16;
                                } else {
                                    let v17: bool = v1 == 6;
                                    if v17 {
                                        let v18: Rc<str> = Rc::<str>::from("6");
                                        v35 = v18;
                                    } else {
                                        let v19: bool = v1 == 7;
                                        if v19 {
                                            let v20: Rc<str> = Rc::<str>::from("7");
                                            v35 = v20;
                                        } else {
                                            let v21: bool = v1 == 8;
                                            if v21 {
                                                let v22: Rc<str> = Rc::<str>::from("8");
                                                v35 = v22;
                                            } else {
                                                let v23: bool = v1 == 9;
                                                if v23 {
                                                    let v24: Rc<str> = Rc::<str>::from("9");
                                                    v35 = v24;
                                                } else {
                                                    let v25: Rc<str> = Rc::<str>::from("0");
                                                    v35 = v25;
                                                }
                                            }
                                        }
                                    }
                                }
                            }
                        }
                    }
                }
            }
            let v37: Rc<str> = Rc::<str>::from("file.txt");
            let v38: Rc<str> = Rc::<str>::from(std::path::Path::new(v0.as_ref()).join(v37.as_ref()).display().to_string());
            let v39: i64 = v1 + 1;
            let v40: Rc<str> = times2(v35.clone(), v39);
            let v41: i32 = 0;
            let v42: i32 = -1;
            let v43: i32 = last_sep3(v38.clone(), v41, v42);
            let v44: bool = v43 == -1;
            let mut v55: Rc<str>;
            if v44 {
                let v45: Rc<str> = Rc::<str>::from("");
                v55 = v45;
            } else {
                let v46: i32 = v43 - 1;
                let v47: Rc<str> = SpiralStringSlice(&v38, 0, v46);
                let v48: i32 = (v47).len() as i32;
                let v49: bool = v48 == 2;
                let mut v52: bool;
                if v49 {
                    let v50: u8 = SpiralStringIndex(&v47, 1);
                    let v51: bool = v50 == 58;
                    v52 = v51;
                } else {
                    v52 = false;
                }
                if v52 {
                    let v53: Rc<str> = SpiralStringSlice(&v38, 0, v43);
                    v55 = v53;
                } else {
                    v55 = v47.clone();
                }
            }
            let v56: i32 = (v55).len() as i32;
            let v57: bool = v56 == 0;
            let mut v60: i32;
            if v57 {
                v60 = 0;
            } else {
                let v59: i32 = i32::from(std::fs::create_dir_all(v55.as_ref()).is_err());
                v60 = v59;
            }
            let v61: bool = v60 == 0;
            let mut v64: i32;
            if v61 {
                let v63: i32 = i32::from(std::fs::write(v38.as_ref(), v40.as_ref().as_bytes()).is_err());
                v64 = v63;
            } else {
                v64 = v60;
            }
            let v66: Rc<str> = Rc::<str>::from(std::path::Path::new(v0.as_ref()).join(v35.as_ref()).display().to_string());
            let v67: i64 = v1 - 1;
            let __spiral_tail_arg0: Rc<str> = v66.clone();
            let __spiral_tail_arg1: i64 = v67;
            v0 = __spiral_tail_arg0;
            v1 = __spiral_tail_arg1;
            continue 'spiral_tail;
        }
    }
}

fn find_nl5(mut v0: Rc<str>, mut v1: i32) -> i32 {
    'spiral_tail: loop {
        let v2: i32 = (v0).len() as i32;
        let v3: bool = v1 == v2;
        if v3 {
            return v1;
        } else {
            let v4: u8 = SpiralStringIndex(&v0, v1);
            let v5: bool = v4 == b'\n';
            if v5 {
                return v1;
            } else {
                let v6: i32 = v1 + 1;
                let __spiral_tail_arg0: Rc<str> = v0.clone();
                let __spiral_tail_arg1: i32 = v6;
                v0 = __spiral_tail_arg0;
                v1 = __spiral_tail_arg1;
                continue 'spiral_tail;
            }
        }
    }
}

fn parse_digits6(mut v0: Rc<str>, mut v1: i32, mut v2: i32, mut v3: i32) -> i32 {
    'spiral_tail: loop {
        let v4: bool = v1 == v2;
        if v4 {
            return v3;
        } else {
            let v5: i32 = v1 + 1;
            let v6: i32 = v3 * 10;
            let v7: u8 = SpiralStringIndex(&v0, v1);
            let v8: bool = v7 == 48;
            let mut v27: i32;
            if v8 {
                v27 = 0;
            } else {
                let v9: bool = v7 == 49;
                if v9 {
                    v27 = 1;
                } else {
                    let v10: bool = v7 == 50;
                    if v10 {
                        v27 = 2;
                    } else {
                        let v11: bool = v7 == 51;
                        if v11 {
                            v27 = 3;
                        } else {
                            let v12: bool = v7 == 52;
                            if v12 {
                                v27 = 4;
                            } else {
                                let v13: bool = v7 == 53;
                                if v13 {
                                    v27 = 5;
                                } else {
                                    let v14: bool = v7 == 54;
                                    if v14 {
                                        v27 = 6;
                                    } else {
                                        let v15: bool = v7 == 55;
                                        if v15 {
                                            v27 = 7;
                                        } else {
                                            let v16: bool = v7 == 56;
                                            if v16 {
                                                v27 = 8;
                                            } else {
                                                let v17: bool = v7 == 57;
                                                if v17 {
                                                    v27 = 9;
                                                } else {
                                                    v27 = 0;
                                                }
                                            }
                                        }
                                    }
                                }
                            }
                        }
                    }
                }
            }
            let v28: i32 = v6 + v27;
            let __spiral_tail_arg0: Rc<str> = v0.clone();
            let __spiral_tail_arg1: i32 = v5;
            let __spiral_tail_arg2: i32 = v2;
            let __spiral_tail_arg3: i32 = v28;
            v0 = __spiral_tail_arg0;
            v1 = __spiral_tail_arg1;
            v2 = __spiral_tail_arg2;
            v3 = __spiral_tail_arg3;
            continue 'spiral_tail;
        }
    }
}

fn parse4(v0: Rc<str>, v1: i32) -> Recursive0 {
    let v2: i32 = (v0).len() as i32;
    let v3: bool = v1 == v2;
    if v3 {
        return RecursiveCreate0_0();
    } else {
        let v5: i32 = v1 + 2;
        let v6: i32 = find_nl5(v0.clone(), v5);
        let v7: i32 = v1 + 2;
        let v8: i32 = 0;
        let v9: i32 = parse_digits6(v0.clone(), v7, v6, v8);
        let v10: i32 = v6 + 1;
        let v11: i32 = v10 + v9;
        let v12: i32 = v11 - 1;
        let v13: Rc<str> = SpiralStringSlice(&v0, v10, v12);
        let v14: u8 = SpiralStringIndex(&v0, v1);
        let v15: bool = v14 == 49;
        let mut v16: i32;
        if v15 {
            v16 = 1;
        } else {
            v16 = 0;
        }
        let v17: i32 = v10 + v9;
        let v18: Recursive0 = parse4(v0.clone(), v17);
        return RecursiveCreate0_1(v16, v13.clone(), v18.clone());
    }
}

fn cmp_at9(mut v0: Rc<str>, mut v1: Rc<str>, mut v2: i32) -> i32 {
    'spiral_tail: loop {
        let v3: i32 = (v0).len() as i32;
        let v4: i32 = (v1).len() as i32;
        let v5: bool = v2 == v3;
        let mut v7: bool;
        if v5 {
            let v6: bool = v2 == v4;
            v7 = v6;
        } else {
            v7 = false;
        }
        if v7 {
            return 0;
        } else {
            let v8: bool = v2 == v3;
            if v8 {
                return -1;
            } else {
                let v9: bool = v2 == v4;
                if v9 {
                    return 1;
                } else {
                    let v10: u8 = SpiralStringIndex(&v0, v2);
                    let v11: u8 = SpiralStringIndex(&v1, v2);
                    let v12: bool = v10 == v11;
                    if v12 {
                        let v13: i32 = v2 + 1;
                        let __spiral_tail_arg0: Rc<str> = v0.clone();
                        let __spiral_tail_arg1: Rc<str> = v1.clone();
                        let __spiral_tail_arg2: i32 = v13;
                        v0 = __spiral_tail_arg0;
                        v1 = __spiral_tail_arg1;
                        v2 = __spiral_tail_arg2;
                        continue 'spiral_tail;
                    } else {
                        let v15: bool = v10 < v11;
                        if v15 {
                            return -1;
                        } else {
                            return 1;
                        }
                    }
                }
            }
        }
    }
}

fn insert8(v0: i32, v1: Rc<str>, v2: Recursive0) -> Recursive0 {
    if RecursiveTag0(&v2) == 1 {
        let v5: i32 = RecursiveField0_0(&v2);
        let v6: Rc<str> = RecursiveField0_1(&v2);
        let v7: Recursive0 = RecursiveField0_2(&v2);
        RecursiveClone0(&v7);
        let v8: bool = v0 == v5;
        let mut v13: bool;
        if v8 {
            let v9: i32 = 0;
            let v10: i32 = cmp_at9(v1.clone(), v6.clone(), v9);
            let v11: bool = v10 < 0;
            v13 = v11;
        } else {
            let v12: bool = v0 > v5;
            v13 = v12;
        }
        if v13 {
            RecursiveDrop0(&v7);
            return RecursiveCreate0_1(v0, v1.clone(), v2.clone());
        } else {
            RecursiveClone0(&v7);
            RecursiveDrop0(&v2);
            let v15: Recursive0 = insert8(v0, v1.clone(), v7.clone());
            drop(v7);
            return RecursiveCreate0_1(v5, v6.clone(), v15.clone());
        }
    } else {
        drop(v2);
        let v3: Recursive0 = RecursiveCreate0_0();
        return RecursiveCreate0_1(v0, v1.clone(), v3.clone());
    }
}

fn sort7(v0: Recursive0) -> Recursive0 {
    if RecursiveTag0(&v0) == 1 {
        let v2: i32 = RecursiveField0_0(&v0);
        let v3: Rc<str> = RecursiveField0_1(&v0);
        let v4: Recursive0 = RecursiveField0_2(&v0);
        RecursiveClone0(&v4);
        RecursiveClone0(&v4);
        RecursiveDrop0(&v0);
        let v5: Recursive0 = sort7(v4.clone());
        drop(v4);
        return insert8(v2, v3.clone(), v5.clone());
    } else {
        drop(v0);
        return RecursiveCreate0_0();
    }
}

fn chain10(v0: Rc<str>, v1: Rc<str>, v2: Recursive0) -> Recursive1 {
    if RecursiveTag0(&v2) == 1 {
        let v4: i32 = RecursiveField0_0(&v2);
        let v5: Rc<str> = RecursiveField0_1(&v2);
        let v6: Recursive0 = RecursiveField0_2(&v2);
        RecursiveClone0(&v6);
        RecursiveClone0(&v6);
        RecursiveDrop0(&v2);
        let v7: Recursive1 = chain10(v0.clone(), v1.clone(), v6.clone());
        drop(v6);
        let v8: bool = v4 == 1;
        if v8 {
            let v10: Rc<str> = Rc::<str>::from(std::path::Path::new(v0.as_ref()).join(v5.as_ref()).display().to_string());
            let v11: i32 = (v1).len() as i32;
            let v12: bool = v11 == 0;
            let mut v15: Rc<str>;
            if v12 {
                v15 = v5.clone();
            } else {
                let v13: Rc<str> = SpiralStringConcat(&v1, &Rc::<str>::from("/"));
                let v14: Rc<str> = SpiralStringConcat(&v13, &v5);
                v15 = v14;
            }
            let v17: Rc<str> = { let mut out = String::new(); if let Ok(read) = std::fs::read_dir(v10.as_ref()) { for entry in read.flatten() { let child = entry.path(); let Some(name) = child.file_name() else { continue }; let name = name.to_string_lossy(); if child.is_dir() { out.push(char::from(49)); } else if child.is_file() { out.push(char::from(48)); } else { continue }; out.push(char::from(32)); out.push_str(&name.len().to_string()); out.push(char::from(10)); out.push_str(&name); } } Rc::<str>::from(out) };
            let v18: i32 = 0;
            let v19: Recursive0 = parse4(v17.clone(), v18);
            RecursiveClone0(&v19);
            let v20: Recursive0 = sort7(v19.clone());
            RecursiveClone0(&v20);
            drop(v19);
            let v21: Recursive1 = chain10(v10.clone(), v15.clone(), v20.clone());
            drop(v20);
            return RecursiveCreate1_2(v5.clone(), v15.clone(), v21.clone(), v7.clone());
        } else {
            let v24: Rc<str> = Rc::<str>::from(std::path::Path::new(v0.as_ref()).join(v5.as_ref()).display().to_string());
            let v26: i64 = std::fs::metadata(v24.as_ref()).map(|meta| meta.len() as i64).unwrap_or(0);
            return RecursiveCreate1_1(v5.clone(), v1.clone(), v26, v7.clone());
        }
    } else {
        drop(v2);
        return RecursiveCreate1_0();
    }
}

fn folder_bytes12(v0: Recursive1) -> i64 {
    if RecursiveTag1(&v0) == 0 {
        RecursiveDrop1(&v0);
        return 0;
    } else {
        if RecursiveTag1(&v0) == 1 {
            let v3: i64 = RecursiveCaseField1_1_2(&v0);
            let v4: Recursive1 = RecursiveCaseField1_1_3(&v0);
            RecursiveClone1(&v4);
            RecursiveClone1(&v4);
            RecursiveDrop1(&v0);
            let v5: i64 = folder_bytes12(v4.clone());
            drop(v4);
            let v6: i64 = v3 + v5;
            return v6;
        } else {
            let v9: Recursive1 = RecursiveCaseField1_2_2(&v0);
            let v10: Recursive1 = RecursiveCaseField1_2_3(&v0);
            RecursiveClone1(&v9);
            RecursiveClone1(&v9);
            RecursiveClone1(&v10);
            drop(v0);
            let v11: i64 = folder_bytes12(v9.clone());
            RecursiveClone1(&v10);
            drop(v9);
            let v12: i64 = folder_bytes12(v10.clone());
            drop(v10);
            let v13: i64 = v11 + v12;
            return v13;
        }
    }
}

fn html_chain11(v0: Recursive1) -> Rc<str> {
    if RecursiveTag1(&v0) == 0 {
        RecursiveDrop1(&v0);
        let v1: Rc<str> = Rc::<str>::from("");
        return v1;
    } else {
        if RecursiveTag1(&v0) == 1 {
            let v2: Rc<str> = RecursiveCaseField1_1_0(&v0);
            let v3: Rc<str> = RecursiveCaseField1_1_1(&v0);
            let v4: i64 = RecursiveCaseField1_1_2(&v0);
            let v5: Recursive1 = RecursiveCaseField1_1_3(&v0);
            RecursiveClone1(&v5);
            RecursiveDrop1(&v0);
            let v6: i32 = (v3).len() as i32;
            let v7: bool = v6 == 0;
            let mut v10: Rc<str>;
            if v7 {
                v10 = v2.clone();
            } else {
                let v8: Rc<str> = SpiralStringConcat(&v3, &Rc::<str>::from("/"));
                let v9: Rc<str> = SpiralStringConcat(&v8, &v2);
                v10 = v9;
            }
            let v11: Rc<str> = SpiralStringConcat(&Rc::<str>::from("&#128196; <a href=\""), &v10);
            let v12: Rc<str> = SpiralStringConcat(&v11, &Rc::<str>::from("\""));
            let v13: Rc<str> = SpiralStringConcat(&v12, &Rc::<str>::from(">"));
            let v14: Rc<str> = SpiralStringConcat(&v13, &v2);
            let v15: Rc<str> = SpiralStringConcat(&v14, &Rc::<str>::from("</a><span> ("));
            let v16: bool = v4 > 1048576;
            let mut v61: Rc<str>;
            if v16 {
                let v17: i64 = v4 * 100;
                let v18: i64 = 1048576 / 2;
                let v19: i64 = v17 + v18;
                let v20: i64 = v19 / 1048576;
                let v21: i64 = v20 / 100;
                let v22: Rc<str> = show_i640(v21);
                let v23: Rc<str> = SpiralStringConcat(&v22, &Rc::<str>::from("."));
                let v24: i64 = v20 % 100;
                let v25: Rc<str> = show_i640(v24);
                let v26: bool = v24 < 10;
                let mut v28: Rc<str>;
                if v26 {
                    let v27: Rc<str> = SpiralStringConcat(&Rc::<str>::from("0"), &v25);
                    v28 = v27;
                } else {
                    v28 = v25.clone();
                }
                let v29: Rc<str> = SpiralStringConcat(&v23, &v28);
                let v30: Rc<str> = SpiralStringConcat(&v29, &Rc::<str>::from(" MB"));
                v61 = v30;
            } else {
                let v31: bool = v4 > 1024;
                if v31 {
                    let v32: i64 = v4 * 100;
                    let v33: i64 = 1024 / 2;
                    let v34: i64 = v32 + v33;
                    let v35: i64 = v34 / 1024;
                    let v36: i64 = v35 / 100;
                    let v37: Rc<str> = show_i640(v36);
                    let v38: Rc<str> = SpiralStringConcat(&v37, &Rc::<str>::from("."));
                    let v39: i64 = v35 % 100;
                    let v40: Rc<str> = show_i640(v39);
                    let v41: bool = v39 < 10;
                    let mut v43: Rc<str>;
                    if v41 {
                        let v42: Rc<str> = SpiralStringConcat(&Rc::<str>::from("0"), &v40);
                        v43 = v42;
                    } else {
                        v43 = v40.clone();
                    }
                    let v44: Rc<str> = SpiralStringConcat(&v38, &v43);
                    let v45: Rc<str> = SpiralStringConcat(&v44, &Rc::<str>::from(" KB"));
                    v61 = v45;
                } else {
                    let v46: i64 = v4 * 100;
                    let v47: i64 = 1 / 2;
                    let v48: i64 = v46 + v47;
                    let v49: i64 = v48 / 1;
                    let v50: i64 = v49 / 100;
                    let v51: Rc<str> = show_i640(v50);
                    let v52: Rc<str> = SpiralStringConcat(&v51, &Rc::<str>::from("."));
                    let v53: i64 = v49 % 100;
                    let v54: Rc<str> = show_i640(v53);
                    let v55: bool = v53 < 10;
                    let mut v57: Rc<str>;
                    if v55 {
                        let v56: Rc<str> = SpiralStringConcat(&Rc::<str>::from("0"), &v54);
                        v57 = v56;
                    } else {
                        v57 = v54.clone();
                    }
                    let v58: Rc<str> = SpiralStringConcat(&v52, &v57);
                    let v59: Rc<str> = SpiralStringConcat(&v58, &Rc::<str>::from(" B"));
                    v61 = v59;
                }
            }
            let v62: Rc<str> = SpiralStringConcat(&v15, &v61);
            let v63: Rc<str> = SpiralStringConcat(&v62, &Rc::<str>::from(")</span>"));
            let v64: Rc<str> = SpiralStringConcat(&Rc::<str>::from("<div>"), &v63);
            let v65: Rc<str> = SpiralStringConcat(&v64, &Rc::<str>::from("</div>"));
            RecursiveClone1(&v5);
            let v66: Rc<str> = html_chain11(v5.clone());
            drop(v5);
            let v67: Rc<str> = SpiralStringConcat(&v65, &v66);
            return v67;
        } else {
            let v68: Rc<str> = RecursiveCaseField1_2_0(&v0);
            let v69: Rc<str> = RecursiveCaseField1_2_1(&v0);
            let v70: Recursive1 = RecursiveCaseField1_2_2(&v0);
            let v71: Recursive1 = RecursiveCaseField1_2_3(&v0);
            RecursiveClone1(&v70);
            RecursiveClone1(&v70);
            RecursiveClone1(&v71);
            drop(v0);
            let v72: i64 = folder_bytes12(v70.clone());
            let v73: Rc<str> = SpiralStringConcat(&Rc::<str>::from("&#128194; <a href=\""), &v69);
            let v74: Rc<str> = SpiralStringConcat(&v73, &Rc::<str>::from("\""));
            let v75: Rc<str> = SpiralStringConcat(&v74, &Rc::<str>::from(">"));
            let v76: Rc<str> = SpiralStringConcat(&v75, &v68);
            let v77: Rc<str> = SpiralStringConcat(&v76, &Rc::<str>::from("</a><span> ("));
            let v78: bool = v72 > 1048576;
            let mut v123: Rc<str>;
            if v78 {
                let v79: i64 = v72 * 100;
                let v80: i64 = 1048576 / 2;
                let v81: i64 = v79 + v80;
                let v82: i64 = v81 / 1048576;
                let v83: i64 = v82 / 100;
                let v84: Rc<str> = show_i640(v83);
                let v85: Rc<str> = SpiralStringConcat(&v84, &Rc::<str>::from("."));
                let v86: i64 = v82 % 100;
                let v87: Rc<str> = show_i640(v86);
                let v88: bool = v86 < 10;
                let mut v90: Rc<str>;
                if v88 {
                    let v89: Rc<str> = SpiralStringConcat(&Rc::<str>::from("0"), &v87);
                    v90 = v89;
                } else {
                    v90 = v87.clone();
                }
                let v91: Rc<str> = SpiralStringConcat(&v85, &v90);
                let v92: Rc<str> = SpiralStringConcat(&v91, &Rc::<str>::from(" MB"));
                v123 = v92;
            } else {
                let v93: bool = v72 > 1024;
                if v93 {
                    let v94: i64 = v72 * 100;
                    let v95: i64 = 1024 / 2;
                    let v96: i64 = v94 + v95;
                    let v97: i64 = v96 / 1024;
                    let v98: i64 = v97 / 100;
                    let v99: Rc<str> = show_i640(v98);
                    let v100: Rc<str> = SpiralStringConcat(&v99, &Rc::<str>::from("."));
                    let v101: i64 = v97 % 100;
                    let v102: Rc<str> = show_i640(v101);
                    let v103: bool = v101 < 10;
                    let mut v105: Rc<str>;
                    if v103 {
                        let v104: Rc<str> = SpiralStringConcat(&Rc::<str>::from("0"), &v102);
                        v105 = v104;
                    } else {
                        v105 = v102.clone();
                    }
                    let v106: Rc<str> = SpiralStringConcat(&v100, &v105);
                    let v107: Rc<str> = SpiralStringConcat(&v106, &Rc::<str>::from(" KB"));
                    v123 = v107;
                } else {
                    let v108: i64 = v72 * 100;
                    let v109: i64 = 1 / 2;
                    let v110: i64 = v108 + v109;
                    let v111: i64 = v110 / 1;
                    let v112: i64 = v111 / 100;
                    let v113: Rc<str> = show_i640(v112);
                    let v114: Rc<str> = SpiralStringConcat(&v113, &Rc::<str>::from("."));
                    let v115: i64 = v111 % 100;
                    let v116: Rc<str> = show_i640(v115);
                    let v117: bool = v115 < 10;
                    let mut v119: Rc<str>;
                    if v117 {
                        let v118: Rc<str> = SpiralStringConcat(&Rc::<str>::from("0"), &v116);
                        v119 = v118;
                    } else {
                        v119 = v116.clone();
                    }
                    let v120: Rc<str> = SpiralStringConcat(&v114, &v119);
                    let v121: Rc<str> = SpiralStringConcat(&v120, &Rc::<str>::from(" B"));
                    v123 = v121;
                }
            }
            let v124: Rc<str> = SpiralStringConcat(&v77, &v123);
            let v125: Rc<str> = SpiralStringConcat(&v124, &Rc::<str>::from(")</span>"));
            let v126: Rc<str> = SpiralStringConcat(&Rc::<str>::from("<details open=\"true\"><summary>"), &v125);
            let v127: Rc<str> = SpiralStringConcat(&v126, &Rc::<str>::from("</summary><div>"));
            RecursiveClone1(&v70);
            let v128: Rc<str> = html_chain11(v70.clone());
            drop(v70);
            let v129: Rc<str> = SpiralStringConcat(&v127, &v128);
            let v130: Rc<str> = SpiralStringConcat(&v129, &Rc::<str>::from("</div></details>"));
            RecursiveClone1(&v71);
            let v131: Rc<str> = html_chain11(v71.clone());
            drop(v71);
            let v132: Rc<str> = SpiralStringConcat(&v130, &v131);
            return v132;
        }
    }
}

fn flag_at13(mut v0: Rc<str>, mut v1: i32, mut v2: i32) -> i32 {
    'spiral_tail: loop {
        let v3: bool = v1 == v2;
        if v3 {
            return -1;
        } else {
            let v5: Rc<str> = Rc::<str>::from(std::env::args().nth(v1 as usize).unwrap_or_default());
            let v6: bool = v5 == v0;
            if v6 {
                return v1;
            } else {
                let v7: i32 = v1 + 1;
                let __spiral_tail_arg0: Rc<str> = v0.clone();
                let __spiral_tail_arg1: i32 = v7;
                let __spiral_tail_arg2: i32 = v2;
                v0 = __spiral_tail_arg0;
                v1 = __spiral_tail_arg1;
                v2 = __spiral_tail_arg2;
                continue 'spiral_tail;
            }
        }
    }
}

fn spiral_main() -> i32 {
    let v1: i32 = std::env::args().count() as i32;
    let v2: bool = v1 == 2;
    if v2 {
        let v4: Rc<str> = Rc::<str>::from(std::env::args().nth(1 as usize).unwrap_or_default());
        let v5: Rc<str> = Rc::<str>::from("--self-test");
        let v6: bool = v4 == v5;
        if v6 {
            let v8: Rc<str> = Rc::<str>::from(std::env::temp_dir().display().to_string());
            let v10: i64 = std::process::id() as i64;
            let v11: Rc<str> = show_i640(v10);
            let v12: Rc<str> = SpiralStringConcat(&v11, &Rc::<str>::from("-"));
            let v14: i64 = std::time::SystemTime::now().duration_since(std::time::UNIX_EPOCH).unwrap().as_nanos() as i64;
            let v15: Rc<str> = show_i640(v14);
            let v16: Rc<str> = SpiralStringConcat(&v12, &v15);
            let v18: Rc<str> = Rc::<str>::from(std::path::Path::new(v8.as_ref()).join(v16.as_ref()).display().to_string());
            let v20: Rc<str> = Rc::<str>::from("_.root");
            let v21: Rc<str> = Rc::<str>::from(std::path::Path::new(v18.as_ref()).join(v20.as_ref()).display().to_string());
            let v22: i64 = 3;
            let v23: i32 = lay1(v21.clone(), v22);
            let v24: Rc<str> = Rc::<str>::from("");
            let v26: Rc<str> = { let mut out = String::new(); if let Ok(read) = std::fs::read_dir(v18.as_ref()) { for entry in read.flatten() { let child = entry.path(); let Some(name) = child.file_name() else { continue }; let name = name.to_string_lossy(); if child.is_dir() { out.push(char::from(49)); } else if child.is_file() { out.push(char::from(48)); } else { continue }; out.push(char::from(32)); out.push_str(&name.len().to_string()); out.push(char::from(10)); out.push_str(&name); } } Rc::<str>::from(out) };
            let v27: i32 = 0;
            let v28: Recursive0 = parse4(v26.clone(), v27);
            RecursiveClone0(&v28);
            let v29: Recursive0 = sort7(v28.clone());
            RecursiveClone0(&v29);
            drop(v28);
            let v30: Recursive1 = chain10(v18.clone(), v24.clone(), v29.clone());
            RecursiveClone1(&v30);
            drop(v29);
            let v31: Rc<str> = html_chain11(v30.clone());
            let v32: Rc<str> = SpiralStringConcat(&Rc::<str>::from("<!DOCTYPE html>\n<html lang=\"en\">\n<head>\n  <meta charset=\"UTF-8\">\n  <style>\nbody {\n    background-color: #222;\n    color: #ccc;\n}\na {\n  color: #777;\n  font-size: 15px;\n}\nspan {\n  font-size: 11px;\n}\ndiv > div {\n  padding-left: 10px;\n}\ndetails > div {\n  padding-left: 19px;\n}\n  </style>\n</head>\n<body>\n  <div>"), &v31);
            let v33: Rc<str> = SpiralStringConcat(&v32, &Rc::<str>::from("</div>\n</body>\n</html>\n"));
            let v34: Rc<str> = Rc::<str>::from("<!DOCTYPE html>\n<html lang=\"en\">\n<head>\n  <meta charset=\"UTF-8\">\n  <style>\nbody {\n    background-color: #222;\n    color: #ccc;\n}\na {\n  color: #777;\n  font-size: 15px;\n}\nspan {\n  font-size: 11px;\n}\ndiv > div {\n  padding-left: 10px;\n}\ndetails > div {\n  padding-left: 19px;\n}\n  </style>\n</head>\n<body>\n  <div><details open=\"true\"><summary>&#128194; <a href=\"_.root\">_.root</a><span> (10.00 B)</span></summary><div><details open=\"true\"><summary>&#128194; <a href=\"_.root/3\">3</a><span> (6.00 B)</span></summary><div><details open=\"true\"><summary>&#128194; <a href=\"_.root/3/2\">2</a><span> (3.00 B)</span></summary><div><details open=\"true\"><summary>&#128194; <a href=\"_.root/3/2/1\">1</a><span> (1.00 B)</span></summary><div><div>&#128196; <a href=\"_.root/3/2/1/file.txt\">file.txt</a><span> (1.00 B)</span></div></div></details><div>&#128196; <a href=\"_.root/3/2/file.txt\">file.txt</a><span> (2.00 B)</span></div></div></details><div>&#128196; <a href=\"_.root/3/file.txt\">file.txt</a><span> (3.00 B)</span></div></div></details><div>&#128196; <a href=\"_.root/file.txt\">file.txt</a><span> (4.00 B)</span></div></div></details></div>\n</body>\n</html>\n");
            let v35: bool = v33 == v34;
            let mut v64: i32;
            if v35 {
                v64 = 0;
            } else {
                let v37: Rc<str> = Rc::<str>::from(std::env::temp_dir().display().to_string());
                let v39: Rc<str> = Rc::<str>::from("dir-tree-html-got.html");
                let v40: Rc<str> = Rc::<str>::from(std::path::Path::new(v37.as_ref()).join(v39.as_ref()).display().to_string());
                let v41: i32 = 0;
                let v42: i32 = -1;
                let v43: i32 = last_sep3(v40.clone(), v41, v42);
                let v44: bool = v43 == -1;
                let mut v54: Rc<str>;
                if v44 {
                    v54 = v24.clone();
                } else {
                    let v45: i32 = v43 - 1;
                    let v46: Rc<str> = SpiralStringSlice(&v40, 0, v45);
                    let v47: i32 = (v46).len() as i32;
                    let v48: bool = v47 == 2;
                    let mut v51: bool;
                    if v48 {
                        let v49: u8 = SpiralStringIndex(&v46, 1);
                        let v50: bool = v49 == 58;
                        v51 = v50;
                    } else {
                        v51 = false;
                    }
                    if v51 {
                        let v52: Rc<str> = SpiralStringSlice(&v40, 0, v43);
                        v54 = v52;
                    } else {
                        v54 = v46.clone();
                    }
                }
                let v55: i32 = (v54).len() as i32;
                let v56: bool = v55 == 0;
                let mut v59: i32;
                if v56 {
                    v59 = 0;
                } else {
                    let v58: i32 = i32::from(std::fs::create_dir_all(v54.as_ref()).is_err());
                    v59 = v58;
                }
                let v60: bool = v59 == 0;
                let mut v63: i32;
                if v60 {
                    let v62: i32 = i32::from(std::fs::write(v40.as_ref(), v33.as_ref().as_bytes()).is_err());
                    v63 = v62;
                } else {
                    v63 = v59;
                }
                v64 = 1;
            }
            RecursiveClone1(&v30);
            let v65: i64 = folder_bytes12(v30.clone());
            drop(v30);
            let v66: bool = v65 == 10;
            let mut v67: i32;
            if v66 {
                v67 = 0;
            } else {
                v67 = 3;
            }
            let v69: Rc<str> = Rc::<str>::from(std::env::temp_dir().display().to_string());
            let v71: i64 = std::process::id() as i64;
            let v72: Rc<str> = show_i640(v71);
            let v73: Rc<str> = SpiralStringConcat(&v72, &Rc::<str>::from("-"));
            let v75: i64 = std::time::SystemTime::now().duration_since(std::time::UNIX_EPOCH).unwrap().as_nanos() as i64;
            let v76: Rc<str> = show_i640(v75);
            let v77: Rc<str> = SpiralStringConcat(&v73, &v76);
            let v79: Rc<str> = Rc::<str>::from(std::path::Path::new(v69.as_ref()).join(v77.as_ref()).display().to_string());
            let v81: Rc<str> = Rc::<str>::from("m");
            let v82: Rc<str> = Rc::<str>::from(std::path::Path::new(v79.as_ref()).join(v81.as_ref()).display().to_string());
            let v84: i32 = i32::from(std::fs::create_dir_all(v82.as_ref()).is_err());
            let v86: Rc<str> = Rc::<str>::from("b.txt");
            let v87: Rc<str> = Rc::<str>::from(std::path::Path::new(v79.as_ref()).join(v86.as_ref()).display().to_string());
            let v88: i32 = 0;
            let v89: i32 = -1;
            let v90: i32 = last_sep3(v87.clone(), v88, v89);
            let v91: bool = v90 == -1;
            let mut v101: Rc<str>;
            if v91 {
                v101 = v24.clone();
            } else {
                let v92: i32 = v90 - 1;
                let v93: Rc<str> = SpiralStringSlice(&v87, 0, v92);
                let v94: i32 = (v93).len() as i32;
                let v95: bool = v94 == 2;
                let mut v98: bool;
                if v95 {
                    let v96: u8 = SpiralStringIndex(&v93, 1);
                    let v97: bool = v96 == 58;
                    v98 = v97;
                } else {
                    v98 = false;
                }
                if v98 {
                    let v99: Rc<str> = SpiralStringSlice(&v87, 0, v90);
                    v101 = v99;
                } else {
                    v101 = v93.clone();
                }
            }
            let v102: i32 = (v101).len() as i32;
            let v103: bool = v102 == 0;
            let mut v106: i32;
            if v103 {
                v106 = 0;
            } else {
                let v105: i32 = i32::from(std::fs::create_dir_all(v101.as_ref()).is_err());
                v106 = v105;
            }
            let v107: bool = v106 == 0;
            let mut v111: i32;
            if v107 {
                let v109: Rc<str> = Rc::<str>::from("x");
                let v110: i32 = i32::from(std::fs::write(v87.as_ref(), v109.as_ref().as_bytes()).is_err());
                v111 = v110;
            } else {
                v111 = v106;
            }
            let v113: Rc<str> = Rc::<str>::from("a.txt");
            let v114: Rc<str> = Rc::<str>::from(std::path::Path::new(v79.as_ref()).join(v113.as_ref()).display().to_string());
            let v115: i32 = 0;
            let v116: i32 = -1;
            let v117: i32 = last_sep3(v114.clone(), v115, v116);
            let v118: bool = v117 == -1;
            let mut v128: Rc<str>;
            if v118 {
                v128 = v24.clone();
            } else {
                let v119: i32 = v117 - 1;
                let v120: Rc<str> = SpiralStringSlice(&v114, 0, v119);
                let v121: i32 = (v120).len() as i32;
                let v122: bool = v121 == 2;
                let mut v125: bool;
                if v122 {
                    let v123: u8 = SpiralStringIndex(&v120, 1);
                    let v124: bool = v123 == 58;
                    v125 = v124;
                } else {
                    v125 = false;
                }
                if v125 {
                    let v126: Rc<str> = SpiralStringSlice(&v114, 0, v117);
                    v128 = v126;
                } else {
                    v128 = v120.clone();
                }
            }
            let v129: i32 = (v128).len() as i32;
            let v130: bool = v129 == 0;
            let mut v133: i32;
            if v130 {
                v133 = 0;
            } else {
                let v132: i32 = i32::from(std::fs::create_dir_all(v128.as_ref()).is_err());
                v133 = v132;
            }
            let v134: bool = v133 == 0;
            let mut v138: i32;
            if v134 {
                let v136: Rc<str> = Rc::<str>::from("yy");
                let v137: i32 = i32::from(std::fs::write(v114.as_ref(), v136.as_ref().as_bytes()).is_err());
                v138 = v137;
            } else {
                v138 = v133;
            }
            let v140: Rc<str> = Rc::<str>::from(std::path::Path::new(v79.as_ref()).join(v81.as_ref()).display().to_string());
            let v142: Rc<str> = Rc::<str>::from("file.txt");
            let v143: Rc<str> = Rc::<str>::from(std::path::Path::new(v140.as_ref()).join(v142.as_ref()).display().to_string());
            let v144: i32 = 0;
            let v145: i32 = -1;
            let v146: i32 = last_sep3(v143.clone(), v144, v145);
            let v147: bool = v146 == -1;
            let mut v157: Rc<str>;
            if v147 {
                v157 = v24.clone();
            } else {
                let v148: i32 = v146 - 1;
                let v149: Rc<str> = SpiralStringSlice(&v143, 0, v148);
                let v150: i32 = (v149).len() as i32;
                let v151: bool = v150 == 2;
                let mut v154: bool;
                if v151 {
                    let v152: u8 = SpiralStringIndex(&v149, 1);
                    let v153: bool = v152 == 58;
                    v154 = v153;
                } else {
                    v154 = false;
                }
                if v154 {
                    let v155: Rc<str> = SpiralStringSlice(&v143, 0, v146);
                    v157 = v155;
                } else {
                    v157 = v149.clone();
                }
            }
            let v158: i32 = (v157).len() as i32;
            let v159: bool = v158 == 0;
            let mut v162: i32;
            if v159 {
                v162 = 0;
            } else {
                let v161: i32 = i32::from(std::fs::create_dir_all(v157.as_ref()).is_err());
                v162 = v161;
            }
            let v163: bool = v162 == 0;
            let mut v167: i32;
            if v163 {
                let v165: Rc<str> = Rc::<str>::from("z");
                let v166: i32 = i32::from(std::fs::write(v143.as_ref(), v165.as_ref().as_bytes()).is_err());
                v167 = v166;
            } else {
                v167 = v162;
            }
            let v169: Rc<str> = { let mut out = String::new(); if let Ok(read) = std::fs::read_dir(v79.as_ref()) { for entry in read.flatten() { let child = entry.path(); let Some(name) = child.file_name() else { continue }; let name = name.to_string_lossy(); if child.is_dir() { out.push(char::from(49)); } else if child.is_file() { out.push(char::from(48)); } else { continue }; out.push(char::from(32)); out.push_str(&name.len().to_string()); out.push(char::from(10)); out.push_str(&name); } } Rc::<str>::from(out) };
            let v170: i32 = 0;
            let v171: Recursive0 = parse4(v169.clone(), v170);
            RecursiveClone0(&v171);
            let v172: Recursive0 = sort7(v171.clone());
            RecursiveClone0(&v172);
            drop(v171);
            let v173: Recursive1 = chain10(v79.clone(), v24.clone(), v172.clone());
            RecursiveClone1(&v173);
            drop(v172);
            let v174: Rc<str> = html_chain11(v173.clone());
            drop(v173);
            let v175: Rc<str> = SpiralStringConcat(&Rc::<str>::from("<!DOCTYPE html>\n<html lang=\"en\">\n<head>\n  <meta charset=\"UTF-8\">\n  <style>\nbody {\n    background-color: #222;\n    color: #ccc;\n}\na {\n  color: #777;\n  font-size: 15px;\n}\nspan {\n  font-size: 11px;\n}\ndiv > div {\n  padding-left: 10px;\n}\ndetails > div {\n  padding-left: 19px;\n}\n  </style>\n</head>\n<body>\n  <div>"), &v174);
            let v176: Rc<str> = SpiralStringConcat(&v175, &Rc::<str>::from("</div>\n</body>\n</html>\n"));
            let v177: Rc<str> = Rc::<str>::from("<!DOCTYPE html>\n<html lang=\"en\">\n<head>\n  <meta charset=\"UTF-8\">\n  <style>\nbody {\n    background-color: #222;\n    color: #ccc;\n}\na {\n  color: #777;\n  font-size: 15px;\n}\nspan {\n  font-size: 11px;\n}\ndiv > div {\n  padding-left: 10px;\n}\ndetails > div {\n  padding-left: 19px;\n}\n  </style>\n</head>\n<body>\n  <div><details open=\"true\"><summary>&#128194; <a href=\"m\">m</a><span> (1.00 B)</span></summary><div><div>&#128196; <a href=\"m/file.txt\">file.txt</a><span> (1.00 B)</span></div></div></details><div>&#128196; <a href=\"a.txt\">a.txt</a><span> (2.00 B)</span></div><div>&#128196; <a href=\"b.txt\">b.txt</a><span> (1.00 B)</span></div></div>\n</body>\n</html>\n");
            let v178: bool = v176 == v177;
            let mut v207: i32;
            if v178 {
                v207 = 0;
            } else {
                let v180: Rc<str> = Rc::<str>::from(std::env::temp_dir().display().to_string());
                let v182: Rc<str> = Rc::<str>::from("dir-tree-html-order-got.html");
                let v183: Rc<str> = Rc::<str>::from(std::path::Path::new(v180.as_ref()).join(v182.as_ref()).display().to_string());
                let v184: i32 = 0;
                let v185: i32 = -1;
                let v186: i32 = last_sep3(v183.clone(), v184, v185);
                let v187: bool = v186 == -1;
                let mut v197: Rc<str>;
                if v187 {
                    v197 = v24.clone();
                } else {
                    let v188: i32 = v186 - 1;
                    let v189: Rc<str> = SpiralStringSlice(&v183, 0, v188);
                    let v190: i32 = (v189).len() as i32;
                    let v191: bool = v190 == 2;
                    let mut v194: bool;
                    if v191 {
                        let v192: u8 = SpiralStringIndex(&v189, 1);
                        let v193: bool = v192 == 58;
                        v194 = v193;
                    } else {
                        v194 = false;
                    }
                    if v194 {
                        let v195: Rc<str> = SpiralStringSlice(&v183, 0, v186);
                        v197 = v195;
                    } else {
                        v197 = v189.clone();
                    }
                }
                let v198: i32 = (v197).len() as i32;
                let v199: bool = v198 == 0;
                let mut v202: i32;
                if v199 {
                    v202 = 0;
                } else {
                    let v201: i32 = i32::from(std::fs::create_dir_all(v197.as_ref()).is_err());
                    v202 = v201;
                }
                let v203: bool = v202 == 0;
                let mut v206: i32;
                if v203 {
                    let v205: i32 = i32::from(std::fs::write(v183.as_ref(), v176.as_ref().as_bytes()).is_err());
                    v206 = v205;
                } else {
                    v206 = v202;
                }
                v207 = 1;
            }
            let v208: i64 = 1024 * 100;
            let v209: i64 = 1 / 2;
            let v210: i64 = v208 + v209;
            let v211: i64 = v210 / 1;
            let v212: i64 = v211 / 100;
            let v213: Rc<str> = show_i640(v212);
            let v214: Rc<str> = SpiralStringConcat(&v213, &Rc::<str>::from("."));
            let v215: i64 = v211 % 100;
            let v216: Rc<str> = show_i640(v215);
            let v217: bool = v215 < 10;
            let mut v219: Rc<str>;
            if v217 {
                let v218: Rc<str> = SpiralStringConcat(&Rc::<str>::from("0"), &v216);
                v219 = v218;
            } else {
                v219 = v216.clone();
            }
            let v220: Rc<str> = SpiralStringConcat(&v214, &v219);
            let v221: Rc<str> = SpiralStringConcat(&v220, &Rc::<str>::from(" B"));
            let v222: Rc<str> = Rc::<str>::from("1024.00 B");
            let v223: bool = v221 == v222;
            let mut v275: i32;
            if v223 {
                let v224: i64 = 1025 * 100;
                let v225: i64 = 1024 / 2;
                let v226: i64 = v224 + v225;
                let v227: i64 = v226 / 1024;
                let v228: i64 = v227 / 100;
                let v229: Rc<str> = show_i640(v228);
                let v230: Rc<str> = SpiralStringConcat(&v229, &Rc::<str>::from("."));
                let v231: i64 = v227 % 100;
                let v232: Rc<str> = show_i640(v231);
                let v233: bool = v231 < 10;
                let mut v235: Rc<str>;
                if v233 {
                    let v234: Rc<str> = SpiralStringConcat(&Rc::<str>::from("0"), &v232);
                    v235 = v234;
                } else {
                    v235 = v232.clone();
                }
                let v236: Rc<str> = SpiralStringConcat(&v230, &v235);
                let v237: Rc<str> = SpiralStringConcat(&v236, &Rc::<str>::from(" KB"));
                let v238: Rc<str> = Rc::<str>::from("1.00 KB");
                let v239: bool = v237 == v238;
                if v239 {
                    let v240: i64 = 1048576 * 100;
                    let v241: i64 = 1024 / 2;
                    let v242: i64 = v240 + v241;
                    let v243: i64 = v242 / 1024;
                    let v244: i64 = v243 / 100;
                    let v245: Rc<str> = show_i640(v244);
                    let v246: Rc<str> = SpiralStringConcat(&v245, &Rc::<str>::from("."));
                    let v247: i64 = v243 % 100;
                    let v248: Rc<str> = show_i640(v247);
                    let v249: bool = v247 < 10;
                    let mut v251: Rc<str>;
                    if v249 {
                        let v250: Rc<str> = SpiralStringConcat(&Rc::<str>::from("0"), &v248);
                        v251 = v250;
                    } else {
                        v251 = v248.clone();
                    }
                    let v252: Rc<str> = SpiralStringConcat(&v246, &v251);
                    let v253: Rc<str> = SpiralStringConcat(&v252, &Rc::<str>::from(" KB"));
                    let v254: Rc<str> = Rc::<str>::from("1024.00 KB");
                    let v255: bool = v253 == v254;
                    if v255 {
                        let v256: i64 = 1048577 * 100;
                        let v257: i64 = 1048576 / 2;
                        let v258: i64 = v256 + v257;
                        let v259: i64 = v258 / 1048576;
                        let v260: i64 = v259 / 100;
                        let v261: Rc<str> = show_i640(v260);
                        let v262: Rc<str> = SpiralStringConcat(&v261, &Rc::<str>::from("."));
                        let v263: i64 = v259 % 100;
                        let v264: Rc<str> = show_i640(v263);
                        let v265: bool = v263 < 10;
                        let mut v267: Rc<str>;
                        if v265 {
                            let v266: Rc<str> = SpiralStringConcat(&Rc::<str>::from("0"), &v264);
                            v267 = v266;
                        } else {
                            v267 = v264.clone();
                        }
                        let v268: Rc<str> = SpiralStringConcat(&v262, &v267);
                        let v269: Rc<str> = SpiralStringConcat(&v268, &Rc::<str>::from(" MB"));
                        let v270: Rc<str> = Rc::<str>::from("1.00 MB");
                        let v271: bool = v269 == v270;
                        if v271 {
                            v275 = 0;
                        } else {
                            v275 = 1;
                        }
                    } else {
                        v275 = 1;
                    }
                } else {
                    v275 = 1;
                }
            } else {
                v275 = 1;
            }
            let v276: bool = v64 == 0;
            if v276 {
                let v277: bool = v67 == 0;
                if v277 {
                    let v278: bool = v207 == 0;
                    if v278 {
                        return v275;
                    } else {
                        return v207;
                    }
                } else {
                    return v67;
                }
            } else {
                return v64;
            }
        } else {
            let v282: Rc<str> = Rc::<str>::from("--dir");
            let v283: i32 = 1;
            let v285: i32 = std::env::args().count() as i32;
            let v286: i32 = flag_at13(v282.clone(), v283, v285);
            let v287: bool = v286 == -1;
            let mut v294: i32;
            if v287 {
                v294 = -1;
            } else {
                let v288: i32 = v286 + 1;
                let v290: i32 = std::env::args().count() as i32;
                let v291: bool = v288 < v290;
                if v291 {
                    let v292: i32 = v286 + 1;
                    v294 = v292;
                } else {
                    v294 = -1;
                }
            }
            let v295: Rc<str> = Rc::<str>::from("--html");
            let v296: i32 = 1;
            let v298: i32 = std::env::args().count() as i32;
            let v299: i32 = flag_at13(v295.clone(), v296, v298);
            let v300: bool = v299 == -1;
            let mut v307: i32;
            if v300 {
                v307 = -1;
            } else {
                let v301: i32 = v299 + 1;
                let v303: i32 = std::env::args().count() as i32;
                let v304: bool = v301 < v303;
                if v304 {
                    let v305: i32 = v299 + 1;
                    v307 = v305;
                } else {
                    v307 = -1;
                }
            }
            let v308: bool = v294 == -1;
            if v308 {
                return 2;
            } else {
                let v309: bool = v307 == -1;
                if v309 {
                    return 2;
                } else {
                    let v311: Rc<str> = Rc::<str>::from(std::env::args().nth(v307 as usize).unwrap_or_default());
                    let v313: Rc<str> = Rc::<str>::from(std::env::args().nth(v294 as usize).unwrap_or_default());
                    let v314: Rc<str> = Rc::<str>::from("");
                    let v316: Rc<str> = { let mut out = String::new(); if let Ok(read) = std::fs::read_dir(v313.as_ref()) { for entry in read.flatten() { let child = entry.path(); let Some(name) = child.file_name() else { continue }; let name = name.to_string_lossy(); if child.is_dir() { out.push(char::from(49)); } else if child.is_file() { out.push(char::from(48)); } else { continue }; out.push(char::from(32)); out.push_str(&name.len().to_string()); out.push(char::from(10)); out.push_str(&name); } } Rc::<str>::from(out) };
                    let v317: i32 = 0;
                    let v318: Recursive0 = parse4(v316.clone(), v317);
                    RecursiveClone0(&v318);
                    let v319: Recursive0 = sort7(v318.clone());
                    RecursiveClone0(&v319);
                    drop(v318);
                    let v320: Recursive1 = chain10(v313.clone(), v314.clone(), v319.clone());
                    RecursiveClone1(&v320);
                    drop(v319);
                    let v321: Rc<str> = html_chain11(v320.clone());
                    drop(v320);
                    let v322: Rc<str> = SpiralStringConcat(&Rc::<str>::from("<!DOCTYPE html>\n<html lang=\"en\">\n<head>\n  <meta charset=\"UTF-8\">\n  <style>\nbody {\n    background-color: #222;\n    color: #ccc;\n}\na {\n  color: #777;\n  font-size: 15px;\n}\nspan {\n  font-size: 11px;\n}\ndiv > div {\n  padding-left: 10px;\n}\ndetails > div {\n  padding-left: 19px;\n}\n  </style>\n</head>\n<body>\n  <div>"), &v321);
                    let v323: Rc<str> = SpiralStringConcat(&v322, &Rc::<str>::from("</div>\n</body>\n</html>\n"));
                    let v324: i32 = 0;
                    let v325: i32 = -1;
                    let v326: i32 = last_sep3(v311.clone(), v324, v325);
                    let v327: bool = v326 == -1;
                    let mut v337: Rc<str>;
                    if v327 {
                        v337 = v314.clone();
                    } else {
                        let v328: i32 = v326 - 1;
                        let v329: Rc<str> = SpiralStringSlice(&v311, 0, v328);
                        let v330: i32 = (v329).len() as i32;
                        let v331: bool = v330 == 2;
                        let mut v334: bool;
                        if v331 {
                            let v332: u8 = SpiralStringIndex(&v329, 1);
                            let v333: bool = v332 == 58;
                            v334 = v333;
                        } else {
                            v334 = false;
                        }
                        if v334 {
                            let v335: Rc<str> = SpiralStringSlice(&v311, 0, v326);
                            v337 = v335;
                        } else {
                            v337 = v329.clone();
                        }
                    }
                    let v338: i32 = (v337).len() as i32;
                    let v339: bool = v338 == 0;
                    let mut v342: i32;
                    if v339 {
                        v342 = 0;
                    } else {
                        let v341: i32 = i32::from(std::fs::create_dir_all(v337.as_ref()).is_err());
                        v342 = v341;
                    }
                    let v343: bool = v342 == 0;
                    if v343 {
                        let v345: i32 = i32::from(std::fs::write(v311.as_ref(), v323.as_ref().as_bytes()).is_err());
                        return v345;
                    } else {
                        return v342;
                    }
                }
            }
        }
    } else {
        let v350: Rc<str> = Rc::<str>::from("--dir");
        let v351: i32 = 1;
        let v353: i32 = std::env::args().count() as i32;
        let v354: i32 = flag_at13(v350.clone(), v351, v353);
        let v355: bool = v354 == -1;
        let mut v362: i32;
        if v355 {
            v362 = -1;
        } else {
            let v356: i32 = v354 + 1;
            let v358: i32 = std::env::args().count() as i32;
            let v359: bool = v356 < v358;
            if v359 {
                let v360: i32 = v354 + 1;
                v362 = v360;
            } else {
                v362 = -1;
            }
        }
        let v363: Rc<str> = Rc::<str>::from("--html");
        let v364: i32 = 1;
        let v366: i32 = std::env::args().count() as i32;
        let v367: i32 = flag_at13(v363.clone(), v364, v366);
        let v368: bool = v367 == -1;
        let mut v375: i32;
        if v368 {
            v375 = -1;
        } else {
            let v369: i32 = v367 + 1;
            let v371: i32 = std::env::args().count() as i32;
            let v372: bool = v369 < v371;
            if v372 {
                let v373: i32 = v367 + 1;
                v375 = v373;
            } else {
                v375 = -1;
            }
        }
        let v376: bool = v362 == -1;
        if v376 {
            return 2;
        } else {
            let v377: bool = v375 == -1;
            if v377 {
                return 2;
            } else {
                let v379: Rc<str> = Rc::<str>::from(std::env::args().nth(v375 as usize).unwrap_or_default());
                let v381: Rc<str> = Rc::<str>::from(std::env::args().nth(v362 as usize).unwrap_or_default());
                let v382: Rc<str> = Rc::<str>::from("");
                let v384: Rc<str> = { let mut out = String::new(); if let Ok(read) = std::fs::read_dir(v381.as_ref()) { for entry in read.flatten() { let child = entry.path(); let Some(name) = child.file_name() else { continue }; let name = name.to_string_lossy(); if child.is_dir() { out.push(char::from(49)); } else if child.is_file() { out.push(char::from(48)); } else { continue }; out.push(char::from(32)); out.push_str(&name.len().to_string()); out.push(char::from(10)); out.push_str(&name); } } Rc::<str>::from(out) };
                let v385: i32 = 0;
                let v386: Recursive0 = parse4(v384.clone(), v385);
                RecursiveClone0(&v386);
                let v387: Recursive0 = sort7(v386.clone());
                RecursiveClone0(&v387);
                drop(v386);
                let v388: Recursive1 = chain10(v381.clone(), v382.clone(), v387.clone());
                RecursiveClone1(&v388);
                drop(v387);
                let v389: Rc<str> = html_chain11(v388.clone());
                drop(v388);
                let v390: Rc<str> = SpiralStringConcat(&Rc::<str>::from("<!DOCTYPE html>\n<html lang=\"en\">\n<head>\n  <meta charset=\"UTF-8\">\n  <style>\nbody {\n    background-color: #222;\n    color: #ccc;\n}\na {\n  color: #777;\n  font-size: 15px;\n}\nspan {\n  font-size: 11px;\n}\ndiv > div {\n  padding-left: 10px;\n}\ndetails > div {\n  padding-left: 19px;\n}\n  </style>\n</head>\n<body>\n  <div>"), &v389);
                let v391: Rc<str> = SpiralStringConcat(&v390, &Rc::<str>::from("</div>\n</body>\n</html>\n"));
                let v392: i32 = 0;
                let v393: i32 = -1;
                let v394: i32 = last_sep3(v379.clone(), v392, v393);
                let v395: bool = v394 == -1;
                let mut v405: Rc<str>;
                if v395 {
                    v405 = v382.clone();
                } else {
                    let v396: i32 = v394 - 1;
                    let v397: Rc<str> = SpiralStringSlice(&v379, 0, v396);
                    let v398: i32 = (v397).len() as i32;
                    let v399: bool = v398 == 2;
                    let mut v402: bool;
                    if v399 {
                        let v400: u8 = SpiralStringIndex(&v397, 1);
                        let v401: bool = v400 == 58;
                        v402 = v401;
                    } else {
                        v402 = false;
                    }
                    if v402 {
                        let v403: Rc<str> = SpiralStringSlice(&v379, 0, v394);
                        v405 = v403;
                    } else {
                        v405 = v397.clone();
                    }
                }
                let v406: i32 = (v405).len() as i32;
                let v407: bool = v406 == 0;
                let mut v410: i32;
                if v407 {
                    v410 = 0;
                } else {
                    let v409: i32 = i32::from(std::fs::create_dir_all(v405.as_ref()).is_err());
                    v410 = v409;
                }
                let v411: bool = v410 == 0;
                if v411 {
                    let v413: i32 = i32::from(std::fs::write(v379.as_ref(), v391.as_ref().as_bytes()).is_err());
                    return v413;
                } else {
                    return v410;
                }
            }
        }
    }
}

fn main() {
    std::process::exit(spiral_main());
}


