[package]
name = "chat_contract"
version.workspace = true
edition = "2021"
license-file.workspace = true
repository.workspace = true

[lib]
crate-type = ["cdylib"]
path = "chat_contract.rs"

[dependencies]
borsh = "1.5"
near-sdk = "=5.11.0"
indexmap = "=2.11.4"
multibase = "=0.9.1"
unsigned-varint = ">=0.8,<1"
sha2 = "0.10"