// Generated by Spiral portable Rust backend.
#![allow(unused_mut, non_snake_case)]

use std::rc::Rc;

fn SpiralStringIndex(value: &Rc<str>, index: i32) -> u8 {
    assert!(index >= 0, "negative Spiral string index");
    let bytes = value.as_bytes();
    let index = index as usize;
    assert!(index < bytes.len(), "Spiral string index out of bounds");
    bytes[index]
}

fn SpiralStringSlice(value: &Rc<str>, from_index: i32, to_index: i32) -> Rc<str> {
    assert!(from_index >= 0, "negative Spiral string slice start");
    let bytes = value.as_bytes();
    let length = bytes.len() as i32;
    if to_index < from_index { return Rc::<str>::from(""); }
    assert!(from_index <= length, "Spiral string slice start out of bounds");
    assert!(to_index < length, "Spiral string slice end out of bounds");
    let from_index = from_index as usize;
    let to_index = to_index as usize;
    let slice = &bytes[from_index..=to_index];
    Rc::<str>::from(std::str::from_utf8(slice).expect("Spiral string slice must preserve UTF-8 boundaries"))
}

fn SpiralStringConcat(left: &Rc<str>, right: &Rc<str>) -> Rc<str> {
    let mut value = String::with_capacity(left.len() + right.len());
    value.push_str(left);
    value.push_str(right);
    Rc::<str>::from(value.into_boxed_str())
}

#[derive(Clone, Copy)]
struct Tuple9000 {
    v0: i32,
    v1: i32,
    v2: i32,
}

fn TupleCreate9000(v0: i32, v1: i32, v2: i32) -> Tuple9000 {
    Tuple9000 { v0, v1, v2 }
}

#[derive(Clone)]
struct Tuple9001 {
    v0: i32,
    v1: Rc<str>,
    v2: Rc<str>,
}

fn TupleCreate9001(v0: i32, v1: Rc<str>, v2: Rc<str>) -> Tuple9001 {
    Tuple9001 { v0, v1, v2 }
}

#[derive(Clone)]
struct Tuple9002 {
    v0: i32,
    v1: Rc<str>,
    v2: i32,
}

fn TupleCreate9002(v0: i32, v1: Rc<str>, v2: i32) -> Tuple9002 {
    Tuple9002 { v0, v1, v2 }
}

fn find_from0(mut v0: Rc<str>, mut v1: i32, mut v2: Rc<str>) -> i32 {
    'spiral_tail: loop {
        let v3: i32 = (v0).len() as i32;
        let v4: i32 = (v2).len() as i32;
        let v5: i32 = v1 + v4;
        let v6: bool = v5 > v3;
        if v6 {
            return -1;
        } else {
            let v7: i32 = v1 + v4;
            let v8: bool = v7 > v3;
            let mut v13: bool;
            if v8 {
                v13 = false;
            } else {
                let v9: i32 = v1 + v4;
                let v10: i32 = v9 - 1;
                let v11: Rc<str> = SpiralStringSlice(&v0, v1, v10);
                let v12: bool = v11 == v2;
                v13 = v12;
            }
            if v13 {
                return v1;
            } else {
                let v14: i32 = v1 + 1;
                let __spiral_tail_arg0: Rc<str> = v0.clone();
                let __spiral_tail_arg1: i32 = v14;
                let __spiral_tail_arg2: Rc<str> = v2.clone();
                v0 = __spiral_tail_arg0;
                v1 = __spiral_tail_arg1;
                v2 = __spiral_tail_arg2;
                continue 'spiral_tail;
            }
        }
    }
}

fn line_start1(mut v0: Rc<str>, mut v1: i32) -> i32 {
    'spiral_tail: loop {
        let v2: bool = v1 == 0;
        if v2 {
            return 0;
        } else {
            let v3: i32 = v1 - 1;
            let v4: u8 = SpiralStringIndex(&v0, v3);
            let v5: bool = v4 == b'\n';
            if v5 {
                return v1;
            } else {
                let v6: i32 = v1 - 1;
                let __spiral_tail_arg0: Rc<str> = v0.clone();
                let __spiral_tail_arg1: i32 = v6;
                v0 = __spiral_tail_arg0;
                v1 = __spiral_tail_arg1;
                continue 'spiral_tail;
            }
        }
    }
}

fn trim_at2(mut v0: Rc<str>, mut v1: i32) -> i32 {
    'spiral_tail: loop {
        let v2: bool = v1 == 0;
        if v2 {
            return 0;
        } else {
            let v3: i32 = v1 - 1;
            let v4: u8 = SpiralStringIndex(&v0, v3);
            let v5: bool = v4 == 32;
            if v5 {
                let v6: i32 = v1 - 1;
                let __spiral_tail_arg0: Rc<str> = v0.clone();
                let __spiral_tail_arg1: i32 = v6;
                v0 = __spiral_tail_arg0.clone();
                v1 = __spiral_tail_arg1;
                continue 'spiral_tail;
            } else {
                let v8: bool = v4 == b'\t';
                if v8 {
                    let v9: i32 = v1 - 1;
                    let __spiral_tail_arg0: Rc<str> = v0.clone();
                    let __spiral_tail_arg1: i32 = v9;
                    v0 = __spiral_tail_arg0.clone();
                    v1 = __spiral_tail_arg1;
                    continue 'spiral_tail;
                } else {
                    let v11: bool = v4 == b'\r';
                    if v11 {
                        let v12: i32 = v1 - 1;
                        let __spiral_tail_arg0: Rc<str> = v0.clone();
                        let __spiral_tail_arg1: i32 = v12;
                        v0 = __spiral_tail_arg0.clone();
                        v1 = __spiral_tail_arg1;
                        continue 'spiral_tail;
                    } else {
                        let v14: bool = v4 == b'\n';
                        if v14 {
                            let v15: i32 = v1 - 1;
                            let __spiral_tail_arg0: Rc<str> = v0.clone();
                            let __spiral_tail_arg1: i32 = v15;
                            v0 = __spiral_tail_arg0.clone();
                            v1 = __spiral_tail_arg1;
                            continue 'spiral_tail;
                        } else {
                            return v1;
                        }
                    }
                }
            }
        }
    }
}

fn last_sep4(mut v0: Rc<str>, mut v1: i32, mut v2: i32) -> i32 {
    'spiral_tail: loop {
        let v3: i32 = (v0).len() as i32;
        let v4: bool = v1 == v3;
        if v4 {
            return v2;
        } else {
            let v5: u8 = SpiralStringIndex(&v0, v1);
            let v6: bool = v5 == 47;
            let mut v9: i32;
            if v6 {
                v9 = v1;
            } else {
                let v7: bool = v5 == b'\\';
                if v7 {
                    v9 = v1;
                } else {
                    v9 = v2;
                }
            }
            let v10: i32 = v1 + 1;
            let __spiral_tail_arg0: Rc<str> = v0.clone();
            let __spiral_tail_arg1: i32 = v10;
            let __spiral_tail_arg2: i32 = v9;
            v0 = __spiral_tail_arg0;
            v1 = __spiral_tail_arg1;
            v2 = __spiral_tail_arg2;
            continue 'spiral_tail;
        }
    }
}

fn find_up3(mut v0: Rc<str>, mut v1: Rc<str>) -> Rc<str> {
    'spiral_tail: loop {
        let v2: Rc<str> = Rc::<str>::from("");
        let v3: bool = v0 == v2;
        if v3 {
            return v2;
        } else {
            let v5: Rc<str> = Rc::<str>::from(std::path::Path::new(v0.as_ref()).join(v1.as_ref()).display().to_string());
            let v7: i32 = i32::from(std::path::Path::new(v5.as_ref()).exists());
            let v8: bool = v7 == 1;
            if v8 {
                return v0;
            } else {
                let v9: i32 = 0;
                let v10: i32 = -1;
                let v11: i32 = last_sep4(v0.clone(), v9, v10);
                let v12: bool = v11 == -1;
                let mut v22: Rc<str>;
                if v12 {
                    v22 = v2.clone();
                } else {
                    let v13: i32 = v11 - 1;
                    let v14: Rc<str> = SpiralStringSlice(&v0, 0, v13);
                    let v15: i32 = (v14).len() as i32;
                    let v16: bool = v15 == 2;
                    let mut v19: bool;
                    if v16 {
                        let v17: u8 = SpiralStringIndex(&v14, 1);
                        let v18: bool = v17 == 58;
                        v19 = v18;
                    } else {
                        v19 = false;
                    }
                    if v19 {
                        let v20: Rc<str> = SpiralStringSlice(&v0, 0, v11);
                        v22 = v20;
                    } else {
                        v22 = v14.clone();
                    }
                }
                let v23: bool = v22 == v2;
                if v23 {
                    return v2;
                } else {
                    let v24: bool = v22 == v0;
                    if v24 {
                        return v2;
                    } else {
                        let __spiral_tail_arg0: Rc<str> = v22.clone();
                        let __spiral_tail_arg1: Rc<str> = v1.clone();
                        v0 = __spiral_tail_arg0;
                        v1 = __spiral_tail_arg1;
                        continue 'spiral_tail;
                    }
                }
            }
        }
    }
}

fn source_at5(mut v0: i32, mut v1: i32) -> Rc<str> {
    'spiral_tail: loop {
        let v2: bool = v0 == v1;
        if v2 {
            let v3: Rc<str> = Rc::<str>::from("");
            return v3;
        } else {
            let v5: Rc<str> = Rc::<str>::from(std::env::args().nth(v0 as usize).unwrap_or_default());
            let v6: i32 = (v5).len() as i32;
            let v7: bool = v6 < 2;
            let mut v11: bool;
            if v7 {
                v11 = false;
            } else {
                let v8: Rc<str> = SpiralStringSlice(&v5, 0, 1);
                let v9: Rc<str> = Rc::<str>::from("--");
                let v10: bool = v8 == v9;
                v11 = v10;
            }
            if v11 {
                let v12: i32 = v0 + 1;
                let __spiral_tail_arg0: i32 = v12;
                let __spiral_tail_arg1: i32 = v1;
                v0 = __spiral_tail_arg0;
                v1 = __spiral_tail_arg1;
                continue 'spiral_tail;
            } else {
                let v15: Rc<str> = Rc::<str>::from(std::env::args().nth(v0 as usize).unwrap_or_default());
                return v15;
            }
        }
    }
}

fn last_dot6(mut v0: Rc<str>, mut v1: i32, mut v2: i32) -> i32 {
    'spiral_tail: loop {
        let v3: i32 = (v0).len() as i32;
        let v4: bool = v1 == v3;
        if v4 {
            return v2;
        } else {
            let v5: u8 = SpiralStringIndex(&v0, v1);
            let v6: bool = v5 == 46;
            let mut v7: i32;
            if v6 {
                v7 = v1;
            } else {
                v7 = v2;
            }
            let v8: i32 = v1 + 1;
            let __spiral_tail_arg0: Rc<str> = v0.clone();
            let __spiral_tail_arg1: i32 = v8;
            let __spiral_tail_arg2: i32 = v7;
            v0 = __spiral_tail_arg0;
            v1 = __spiral_tail_arg1;
            v2 = __spiral_tail_arg2;
            continue 'spiral_tail;
        }
    }
}

fn find_flag7(mut v0: Rc<str>, mut v1: i32, mut v2: i32) -> i32 {
    'spiral_tail: loop {
        let v3: bool = v1 == v2;
        if v3 {
            return -1;
        } else {
            let v5: Rc<str> = Rc::<str>::from(std::env::args().nth(v1 as usize).unwrap_or_default());
            let v6: bool = v5 == v0;
            if v6 {
                return v1;
            } else {
                let v7: i32 = v1 + 1;
                let __spiral_tail_arg0: Rc<str> = v0.clone();
                let __spiral_tail_arg1: i32 = v7;
                let __spiral_tail_arg2: i32 = v2;
                v0 = __spiral_tail_arg0;
                v1 = __spiral_tail_arg1;
                v2 = __spiral_tail_arg2;
                continue 'spiral_tail;
            }
        }
    }
}

fn module_lines8(mut v0: i32, mut v1: i32, mut v2: Rc<str>, mut v3: Rc<str>, mut v4: i32) -> Rc<str> {
    'spiral_tail: loop {
        let v5: bool = v0 == v1;
        if v5 {
            return v3;
        } else {
            let v7: Rc<str> = Rc::<str>::from(std::env::args().nth(v0 as usize).unwrap_or_default());
            let v8: i32 = (v7).len() as i32;
            let v9: bool = v8 < 2;
            let mut v13: bool;
            if v9 {
                v13 = false;
            } else {
                let v10: Rc<str> = SpiralStringSlice(&v7, 0, 1);
                let v11: Rc<str> = Rc::<str>::from("--");
                let v12: bool = v10 == v11;
                v13 = v12;
            }
            if v13 {
                return v3;
            } else {
                let v15: Rc<str> = Rc::<str>::from(std::env::args().nth(v0 as usize).unwrap_or_default());
                let v17: Rc<str> = Rc::<str>::from(std::path::Path::new(v2.as_ref()).join(v15.as_ref()).display().to_string());
                let v18: Rc<str> = SpiralStringConcat(&Rc::<str>::from("<Compile Include=\""), &v17);
                let v19: Rc<str> = SpiralStringConcat(&v18, &Rc::<str>::from("\" />"));
                let v20: bool = v4 == 1;
                let mut v23: Rc<str>;
                if v20 {
                    v23 = v19.clone();
                } else {
                    let v21: Rc<str> = SpiralStringConcat(&v3, &Rc::<str>::from("\n        "));
                    let v22: Rc<str> = SpiralStringConcat(&v21, &v19);
                    v23 = v22;
                }
                let v24: i32 = v0 + 1;
                let v25: i32 = 0;
                let __spiral_tail_arg0: i32 = v24;
                let __spiral_tail_arg1: i32 = v1;
                let __spiral_tail_arg2: Rc<str> = v2.clone();
                let __spiral_tail_arg3: Rc<str> = v23.clone();
                let __spiral_tail_arg4: i32 = v25;
                v0 = __spiral_tail_arg0;
                v1 = __spiral_tail_arg1;
                v2 = __spiral_tail_arg2;
                v3 = __spiral_tail_arg3;
                v4 = __spiral_tail_arg4;
                continue 'spiral_tail;
            }
        }
    }
}

fn join_args9(mut v0: i32, mut v1: i32, mut v2: Rc<str>, mut v3: i32) -> Rc<str> {
    'spiral_tail: loop {
        let v4: bool = v0 == v1;
        if v4 {
            return v2;
        } else {
            let v6: Rc<str> = Rc::<str>::from(std::env::args().nth(v0 as usize).unwrap_or_default());
            let v7: i32 = (v6).len() as i32;
            let v8: bool = v7 < 2;
            let mut v12: bool;
            if v8 {
                v12 = false;
            } else {
                let v9: Rc<str> = SpiralStringSlice(&v6, 0, 1);
                let v10: Rc<str> = Rc::<str>::from("--");
                let v11: bool = v9 == v10;
                v12 = v11;
            }
            if v12 {
                return v2;
            } else {
                let v14: Rc<str> = Rc::<str>::from(std::env::args().nth(v0 as usize).unwrap_or_default());
                let v15: bool = v3 == 1;
                let mut v18: Rc<str>;
                if v15 {
                    v18 = v14.clone();
                } else {
                    let v16: Rc<str> = SpiralStringConcat(&v2, &Rc::<str>::from("\n"));
                    let v17: Rc<str> = SpiralStringConcat(&v16, &v14);
                    v18 = v17;
                }
                let v19: i32 = v0 + 1;
                let v20: i32 = 0;
                let __spiral_tail_arg0: i32 = v19;
                let __spiral_tail_arg1: i32 = v1;
                let __spiral_tail_arg2: Rc<str> = v18.clone();
                let __spiral_tail_arg3: i32 = v20;
                v0 = __spiral_tail_arg0;
                v1 = __spiral_tail_arg1;
                v2 = __spiral_tail_arg2;
                v3 = __spiral_tail_arg3;
                continue 'spiral_tail;
            }
        }
    }
}

fn publish10(v0: Tuple9001, v1: Tuple9002) -> i32 {
    if v0.v0 == 0 {
        let v2: Rc<str> = v0.v1.clone();
        let v3: Rc<str> = v0.v2.clone();
        if v0.v0 == 0 {
            drop(v0.v1);
        }
        if v0.v0 == 0 {
            drop(v0.v2);
        }
        let mut v99: i32;
        if v1.v0 == 0 {
            let v4: Rc<str> = v1.v1.clone();
            let v5: Rc<str> = SpiralStringConcat(&Rc::<str>::from("publish\n"), &v2);
            let v6: Rc<str> = SpiralStringConcat(&v5, &Rc::<str>::from("\n"));
            let v7: Rc<str> = SpiralStringConcat(&v6, &Rc::<str>::from("--configuration"));
            let v8: Rc<str> = SpiralStringConcat(&v7, &Rc::<str>::from("\n"));
            let v9: Rc<str> = SpiralStringConcat(&v8, &Rc::<str>::from("Release"));
            let v10: Rc<str> = SpiralStringConcat(&v9, &Rc::<str>::from("\n"));
            let v11: Rc<str> = SpiralStringConcat(&v10, &Rc::<str>::from("--output"));
            let v12: Rc<str> = SpiralStringConcat(&v11, &Rc::<str>::from("\n"));
            let v13: Rc<str> = SpiralStringConcat(&v12, &v3);
            let v14: Rc<str> = SpiralStringConcat(&v13, &Rc::<str>::from("\n"));
            let v15: Rc<str> = SpiralStringConcat(&v14, &Rc::<str>::from("--runtime"));
            let v16: Rc<str> = SpiralStringConcat(&v15, &Rc::<str>::from("\n"));
            let v17: Rc<str> = SpiralStringConcat(&v16, &v4);
            let v18: i32 = 0;
            let v19: i32 = -1;
            let v20: i32 = last_sep4(v2.clone(), v18, v19);
            let v21: bool = v20 == -1;
            let mut v32: Rc<str>;
            if v21 {
                let v22: Rc<str> = Rc::<str>::from("");
                v32 = v22;
            } else {
                let v23: i32 = v20 - 1;
                let v24: Rc<str> = SpiralStringSlice(&v2, 0, v23);
                let v25: i32 = (v24).len() as i32;
                let v26: bool = v25 == 2;
                let mut v29: bool;
                if v26 {
                    let v27: u8 = SpiralStringIndex(&v24, 1);
                    let v28: bool = v27 == 58;
                    v29 = v28;
                } else {
                    v29 = false;
                }
                if v29 {
                    let v30: Rc<str> = SpiralStringSlice(&v2, 0, v20);
                    v32 = v30;
                } else {
                    v32 = v24.clone();
                }
            }
            let v33: i32 = (v32).len() as i32;
            let v34: bool = v33 == 0;
            let mut v36: Rc<str>;
            if v34 {
                let v35: Rc<str> = Rc::<str>::from(".");
                v36 = v35;
            } else {
                v36 = v32.clone();
            }
            let v38: Rc<str> = Rc::<str>::from("dotnet");
            let v39: i32 = { let mut command = std::process::Command::new(v38.as_ref()); command.args(v17.as_ref().split(char::from(10)).filter(|arg| arg.is_empty() == false)); let status = command.current_dir(v36.as_ref()).status(); status.map(|status| status.code().unwrap_or(1)).unwrap_or(1) };
            v99 = v39;
        } else {
            if v1.v0 == 1 {
                let v40: Rc<str> = SpiralStringConcat(&Rc::<str>::from("publish\n"), &v2);
                let v41: Rc<str> = SpiralStringConcat(&v40, &Rc::<str>::from("\n"));
                let v42: Rc<str> = SpiralStringConcat(&v41, &Rc::<str>::from("--configuration"));
                let v43: Rc<str> = SpiralStringConcat(&v42, &Rc::<str>::from("\n"));
                let v44: Rc<str> = SpiralStringConcat(&v43, &Rc::<str>::from("Release"));
                let v45: Rc<str> = SpiralStringConcat(&v44, &Rc::<str>::from("\n"));
                let v46: Rc<str> = SpiralStringConcat(&v45, &Rc::<str>::from("--output"));
                let v47: Rc<str> = SpiralStringConcat(&v46, &Rc::<str>::from("\n"));
                let v48: Rc<str> = SpiralStringConcat(&v47, &v3);
                let v49: Rc<str> = SpiralStringConcat(&v48, &Rc::<str>::from("\n"));
                let v50: Rc<str> = SpiralStringConcat(&v49, &Rc::<str>::from("--runtime"));
                let v51: Rc<str> = SpiralStringConcat(&v50, &Rc::<str>::from("\n"));
                let v52: Rc<str> = SpiralStringConcat(&v51, &Rc::<str>::from("linux-x64"));
                let v53: i32 = 0;
                let v54: i32 = -1;
                let v55: i32 = last_sep4(v2.clone(), v53, v54);
                let v56: bool = v55 == -1;
                let mut v67: Rc<str>;
                if v56 {
                    let v57: Rc<str> = Rc::<str>::from("");
                    v67 = v57;
                } else {
                    let v58: i32 = v55 - 1;
                    let v59: Rc<str> = SpiralStringSlice(&v2, 0, v58);
                    let v60: i32 = (v59).len() as i32;
                    let v61: bool = v60 == 2;
                    let mut v64: bool;
                    if v61 {
                        let v62: u8 = SpiralStringIndex(&v59, 1);
                        let v63: bool = v62 == 58;
                        v64 = v63;
                    } else {
                        v64 = false;
                    }
                    if v64 {
                        let v65: Rc<str> = SpiralStringSlice(&v2, 0, v55);
                        v67 = v65;
                    } else {
                        v67 = v59.clone();
                    }
                }
                let v68: i32 = (v67).len() as i32;
                let v69: bool = v68 == 0;
                let mut v71: Rc<str>;
                if v69 {
                    let v70: Rc<str> = Rc::<str>::from(".");
                    v71 = v70;
                } else {
                    v71 = v67.clone();
                }
                let v73: Rc<str> = Rc::<str>::from("dotnet");
                let v74: i32 = { let mut command = std::process::Command::new(v73.as_ref()); command.args(v52.as_ref().split(char::from(10)).filter(|arg| arg.is_empty() == false)); let status = command.current_dir(v71.as_ref()).status(); status.map(|status| status.code().unwrap_or(1)).unwrap_or(1) };
                let v75: Rc<str> = SpiralStringConcat(&v51, &Rc::<str>::from("win-x64"));
                let v76: i32 = 0;
                let v77: i32 = -1;
                let v78: i32 = last_sep4(v2.clone(), v76, v77);
                let v79: bool = v78 == -1;
                let mut v90: Rc<str>;
                if v79 {
                    let v80: Rc<str> = Rc::<str>::from("");
                    v90 = v80;
                } else {
                    let v81: i32 = v78 - 1;
                    let v82: Rc<str> = SpiralStringSlice(&v2, 0, v81);
                    let v83: i32 = (v82).len() as i32;
                    let v84: bool = v83 == 2;
                    let mut v87: bool;
                    if v84 {
                        let v85: u8 = SpiralStringIndex(&v82, 1);
                        let v86: bool = v85 == 58;
                        v87 = v86;
                    } else {
                        v87 = false;
                    }
                    if v87 {
                        let v88: Rc<str> = SpiralStringSlice(&v2, 0, v78);
                        v90 = v88;
                    } else {
                        v90 = v82.clone();
                    }
                }
                let v91: i32 = (v90).len() as i32;
                let v92: bool = v91 == 0;
                let mut v94: Rc<str>;
                if v92 {
                    let v93: Rc<str> = Rc::<str>::from(".");
                    v94 = v93;
                } else {
                    v94 = v90.clone();
                }
                let v96: i32 = { let mut command = std::process::Command::new(v73.as_ref()); command.args(v75.as_ref().split(char::from(10)).filter(|arg| arg.is_empty() == false)); let status = command.current_dir(v94.as_ref()).status(); status.map(|status| status.code().unwrap_or(1)).unwrap_or(1) };
                let v97: i32 = v74 + v96;
                v99 = v97;
            } else {
                std::process::abort();
            }
        }
        if v1.v0 == 0 {
            drop(v1.v1);
        }
        let v101: Rc<str> = Rc::<str>::from("CI");
        let v102: Rc<str> = Rc::<str>::from(std::env::var(v101.as_ref()).unwrap_or_default());
        let v103: i32 = (v102).len() as i32;
        let v104: bool = v103 == 0;
        let mut v105: i32;
        if v104 {
            v105 = 0;
        } else {
            v105 = 1;
        }
        let v106: bool = v105 == 1;
        if v106 {
            let v108: Rc<str> = Rc::<str>::from(std::path::absolute(v2.as_ref()).unwrap_or_else(|_| std::path::PathBuf::from(v2.as_ref())).display().to_string());
            let v109: i32 = 0;
            let v110: i32 = -1;
            let v111: i32 = last_sep4(v108.clone(), v109, v110);
            let v112: bool = v111 == -1;
            let mut v123: Rc<str>;
            if v112 {
                let v113: Rc<str> = Rc::<str>::from("");
                v123 = v113;
            } else {
                let v114: i32 = v111 - 1;
                let v115: Rc<str> = SpiralStringSlice(&v108, 0, v114);
                let v116: i32 = (v115).len() as i32;
                let v117: bool = v116 == 2;
                let mut v120: bool;
                if v117 {
                    let v118: u8 = SpiralStringIndex(&v115, 1);
                    let v119: bool = v118 == 58;
                    v120 = v119;
                } else {
                    v120 = false;
                }
                if v120 {
                    let v121: Rc<str> = SpiralStringSlice(&v108, 0, v111);
                    v123 = v121;
                } else {
                    v123 = v115.clone();
                }
            }
            let v125: Rc<str> = Rc::<str>::from("bin");
            let v126: Rc<str> = Rc::<str>::from(std::path::Path::new(v123.as_ref()).join(v125.as_ref()).display().to_string());
            let v128: i32 = i32::from(std::path::Path::new(v126.as_ref()).is_dir());
            let v129: bool = v128 == 1;
            let mut v134: i32;
            if v129 {
                let v131: i32 = i32::from(std::fs::remove_dir_all(v126.as_ref()).is_err());
                v134 = v131;
            } else {
                let v133: i32 = i32::from(std::fs::remove_file(v126.as_ref()).is_err());
                v134 = v133;
            }
            let v136: Rc<str> = Rc::<str>::from("obj");
            let v137: Rc<str> = Rc::<str>::from(std::path::Path::new(v123.as_ref()).join(v136.as_ref()).display().to_string());
            let v139: i32 = i32::from(std::path::Path::new(v137.as_ref()).is_dir());
            let v140: bool = v139 == 1;
            let mut v145: i32;
            if v140 {
                let v142: i32 = i32::from(std::fs::remove_dir_all(v137.as_ref()).is_err());
                v145 = v142;
            } else {
                let v144: i32 = i32::from(std::fs::remove_file(v137.as_ref()).is_err());
                v145 = v144;
            }
            return v99;
        } else {
            return v99;
        }
    } else {
        std::process::abort();
    }
}

fn spiral_main() -> i32 {
    let v1: i32 = std::env::args().count() as i32;
    let v2: bool = v1 == 2;
    let mut v11: Tuple9000;
    if v2 {
        let v4: Rc<str> = Rc::<str>::from(std::env::args().nth(1 as usize).unwrap_or_default());
        let v5: Rc<str> = Rc::<str>::from("--self-test");
        let v6: bool = v4 == v5;
        if v6 {
            v11 = TupleCreate9000(0, 0, 0);
        } else {
            v11 = TupleCreate9000(1, 0, 0);
        }
    } else {
        v11 = TupleCreate9000(1, 0, 0);
    }
    if v11.v0 == 0 {
        let v12: Rc<str> = Rc::<str>::from("    let main args = 0\n()\n");
        let v13: i32 = 0;
        let v14: Rc<str> = Rc::<str>::from("let main");
        let v15: i32 = find_from0(v12.clone(), v13, v14.clone());
        let v16: bool = v15 == -1;
        let mut v28: Rc<str>;
        if v16 {
            v28 = v12.clone();
        } else {
            let v17: i32 = line_start1(v12.clone(), v15);
            let v18: i32 = v15 - 1;
            let v19: Rc<str> = SpiralStringSlice(&Rc::<str>::from("    let main args = 0\n()\n"), v17, v18);
            let v20: i32 = 25 - 1;
            let v21: Rc<str> = SpiralStringSlice(&Rc::<str>::from("    let main args = 0\n()\n"), v15, v20);
            let v22: i32 = v17 - 1;
            let v23: Rc<str> = SpiralStringSlice(&Rc::<str>::from("    let main args = 0\n()\n"), 0, v22);
            let v24: Rc<str> = SpiralStringConcat(&v23, &v19);
            let v25: Rc<str> = SpiralStringConcat(&v24, &Rc::<str>::from("[<EntryPoint>]\n"));
            let v26: Rc<str> = SpiralStringConcat(&v25, &v19);
            let v27: Rc<str> = SpiralStringConcat(&v26, &v21);
            v28 = v27;
        }
        let v29: i32 = (v28).len() as i32;
        let v30: i32 = trim_at2(v28.clone(), v29);
        let v31: i32 = v30 - 1;
        let v32: Rc<str> = SpiralStringSlice(&v28, 0, v31);
        let v33: i32 = (v32).len() as i32;
        let v34: bool = v33 < 3;
        let mut v43: Rc<str>;
        if v34 {
            v43 = v28.clone();
        } else {
            let v35: i32 = v33 - 3;
            let v36: i32 = v33 - 1;
            let v37: Rc<str> = SpiralStringSlice(&v32, v35, v36);
            let v38: Rc<str> = Rc::<str>::from("\n()");
            let v39: bool = v37 == v38;
            if v39 {
                let v40: i32 = v33 - 4;
                let v41: Rc<str> = SpiralStringSlice(&v32, 0, v40);
                v43 = v41;
            } else {
                v43 = v28.clone();
            }
        }
        let v44: Rc<str> = Rc::<str>::from("let x = 1\n    let main args = 0\n()\n");
        let v45: i32 = 0;
        let v46: i32 = find_from0(v44.clone(), v45, v14.clone());
        let v47: bool = v46 == -1;
        let mut v59: Rc<str>;
        if v47 {
            v59 = v44.clone();
        } else {
            let v48: i32 = line_start1(v44.clone(), v46);
            let v49: i32 = v46 - 1;
            let v50: Rc<str> = SpiralStringSlice(&Rc::<str>::from("let x = 1\n    let main args = 0\n()\n"), v48, v49);
            let v51: i32 = 35 - 1;
            let v52: Rc<str> = SpiralStringSlice(&Rc::<str>::from("let x = 1\n    let main args = 0\n()\n"), v46, v51);
            let v53: i32 = v48 - 1;
            let v54: Rc<str> = SpiralStringSlice(&Rc::<str>::from("let x = 1\n    let main args = 0\n()\n"), 0, v53);
            let v55: Rc<str> = SpiralStringConcat(&v54, &v50);
            let v56: Rc<str> = SpiralStringConcat(&v55, &Rc::<str>::from("[<EntryPoint>]\n"));
            let v57: Rc<str> = SpiralStringConcat(&v56, &v50);
            let v58: Rc<str> = SpiralStringConcat(&v57, &v52);
            v59 = v58;
        }
        let v60: i32 = (v59).len() as i32;
        let v61: i32 = trim_at2(v59.clone(), v60);
        let v62: i32 = v61 - 1;
        let v63: Rc<str> = SpiralStringSlice(&v59, 0, v62);
        let v64: i32 = (v63).len() as i32;
        let v65: bool = v64 < 3;
        let mut v74: Rc<str>;
        if v65 {
            v74 = v59.clone();
        } else {
            let v66: i32 = v64 - 3;
            let v67: i32 = v64 - 1;
            let v68: Rc<str> = SpiralStringSlice(&v63, v66, v67);
            let v69: Rc<str> = Rc::<str>::from("\n()");
            let v70: bool = v68 == v69;
            if v70 {
                let v71: i32 = v64 - 4;
                let v72: Rc<str> = SpiralStringSlice(&v63, 0, v71);
                v74 = v72;
            } else {
                v74 = v59.clone();
            }
        }
        let v75: Rc<str> = Rc::<str>::from("    [<EntryPoint>]\n    let main args = 0");
        let v76: bool = v43 == v75;
        if v76 {
            let v77: Rc<str> = Rc::<str>::from("let x = 1\n    [<EntryPoint>]\n    let main args = 0");
            let v78: bool = v74 == v77;
            if v78 {
                return 0;
            } else {
                return 1;
            }
        } else {
            return 1;
        }
    } else {
        if v11.v0 == 1 {
            let v82: Rc<str> = Rc::<str>::from("spiral");
            let v83: Rc<str> = Rc::<str>::from("workspace");
            let v84: Rc<str> = Rc::<str>::from(std::path::Path::new(v82.as_ref()).join(v83.as_ref()).display().to_string());
            let v86: Rc<str> = Rc::<str>::from(std::env::current_dir().map(|path| path.display().to_string()).unwrap_or_default());
            let v87: Rc<str> = find_up3(v86.clone(), v84.clone());
            let v88: Rc<str> = Rc::<str>::from("");
            let v89: bool = v87 == v88;
            let mut v93: Rc<str>;
            if v89 {
                let v91: Rc<str> = Rc::<str>::from(std::env::current_exe().ok().and_then(|path| path.parent().map(|dir| dir.to_path_buf())).map(|path| path.display().to_string()).unwrap_or_default());
                v93 = find_up3(v91.clone(), v84.clone());
            } else {
                v93 = v87.clone();
            }
            let v94: bool = v93 == v88;
            let mut v97: Rc<str>;
            if v94 {
                let v95: Rc<str> = Rc::<str>::from("/workspaces");
                v97 = find_up3(v95.clone(), v84.clone());
            } else {
                v97 = v93.clone();
            }
            let v98: bool = v97 == v88;
            let mut v129: Rc<str>;
            if v98 {
                v129 = v88.clone();
            } else {
                let v99: i32 = 0;
                let v100: i32 = -1;
                let v101: i32 = last_sep4(v97.clone(), v99, v100);
                let v102: i32 = (v97).len() as i32;
                let v103: bool = v101 == -1;
                let mut v110: Rc<str>;
                if v103 {
                    v110 = v97.clone();
                } else {
                    let v104: i32 = v101 + 1;
                    let v105: bool = v104 == v102;
                    if v105 {
                        v110 = v88.clone();
                    } else {
                        let v106: i32 = v101 + 1;
                        let v107: i32 = v102 - 1;
                        let v108: Rc<str> = SpiralStringSlice(&v97, v106, v107);
                        v110 = v108;
                    }
                }
                let v111: Rc<str> = Rc::<str>::from("deps");
                let v112: bool = v110 == v111;
                if v112 {
                    let v113: i32 = 0;
                    let v114: i32 = -1;
                    let v115: i32 = last_sep4(v97.clone(), v113, v114);
                    let v116: bool = v115 == -1;
                    let mut v126: Rc<str>;
                    if v116 {
                        v126 = v88.clone();
                    } else {
                        let v117: i32 = v115 - 1;
                        let v118: Rc<str> = SpiralStringSlice(&v97, 0, v117);
                        let v119: i32 = (v118).len() as i32;
                        let v120: bool = v119 == 2;
                        let mut v123: bool;
                        if v120 {
                            let v121: u8 = SpiralStringIndex(&v118, 1);
                            let v122: bool = v121 == 58;
                            v123 = v122;
                        } else {
                            v123 = false;
                        }
                        if v123 {
                            let v124: Rc<str> = SpiralStringSlice(&v97, 0, v115);
                            v126 = v124;
                        } else {
                            v126 = v118.clone();
                        }
                    }
                    v129 = find_up3(v126.clone(), v84.clone());
                } else {
                    v129 = v97.clone();
                }
            }
            let v130: bool = v129 == v88;
            let mut v134: Rc<str>;
            if v130 {
                v134 = v88.clone();
            } else {
                let v132: Rc<str> = Rc::<str>::from("polyglot");
                let v133: Rc<str> = Rc::<str>::from(std::path::Path::new(v129.as_ref()).join(v132.as_ref()).display().to_string());
                v134 = v133;
            }
            let v135: bool = v134 == v88;
            let mut v156: Rc<str>;
            if v135 {
                let v137: Rc<str> = Rc::<str>::from(std::env::current_dir().map(|path| path.display().to_string()).unwrap_or_default());
                let v138: Rc<str> = Rc::<str>::from(".paket/Paket.Restore.targets");
                let v139: Rc<str> = find_up3(v137.clone(), v138.clone());
                let v140: bool = v139 == v88;
                if v140 {
                    let v141: Rc<str> = Rc::<str>::from(".");
                    v156 = v141;
                } else {
                    v156 = v139.clone();
                }
            } else {
                let v144: Rc<str> = Rc::<str>::from(".paket/Paket.Restore.targets");
                let v145: Rc<str> = Rc::<str>::from(std::path::Path::new(v134.as_ref()).join(v144.as_ref()).display().to_string());
                let v147: i32 = i32::from(std::path::Path::new(v145.as_ref()).exists());
                let v148: bool = v147 == 1;
                if v148 {
                    v156 = v134.clone();
                } else {
                    let v150: Rc<str> = Rc::<str>::from(std::env::current_dir().map(|path| path.display().to_string()).unwrap_or_default());
                    let v151: Rc<str> = find_up3(v150.clone(), v144.clone());
                    let v152: bool = v151 == v88;
                    if v152 {
                        let v153: Rc<str> = Rc::<str>::from(".");
                        v156 = v153;
                    } else {
                        v156 = v151.clone();
                    }
                }
            }
            let v157: i32 = 1;
            let v159: i32 = std::env::args().count() as i32;
            let v160: Rc<str> = source_at5(v157, v159);
            let v162: Rc<str> = Rc::<str>::from(std::path::absolute(v160.as_ref()).unwrap_or_else(|_| std::path::PathBuf::from(v160.as_ref())).display().to_string());
            let v163: i32 = 0;
            let v164: i32 = -1;
            let v165: i32 = last_sep4(v162.clone(), v163, v164);
            let v166: i32 = (v162).len() as i32;
            let v167: bool = v165 == -1;
            let mut v174: Rc<str>;
            if v167 {
                v174 = v162.clone();
            } else {
                let v168: i32 = v165 + 1;
                let v169: bool = v168 == v166;
                if v169 {
                    v174 = v88.clone();
                } else {
                    let v170: i32 = v165 + 1;
                    let v171: i32 = v166 - 1;
                    let v172: Rc<str> = SpiralStringSlice(&v162, v170, v171);
                    v174 = v172;
                }
            }
            let v175: i32 = 0;
            let v176: i32 = -1;
            let v177: i32 = last_dot6(v174.clone(), v175, v176);
            let v178: bool = v177 <= 0;
            let mut v181: Rc<str>;
            if v178 {
                v181 = v174.clone();
            } else {
                let v179: i32 = v177 - 1;
                let v180: Rc<str> = SpiralStringSlice(&v174, 0, v179);
                v181 = v180;
            }
            let v183: Rc<str> = { let path = std::path::absolute(v160.as_ref()).unwrap_or_else(|_| std::path::PathBuf::from(v160.as_ref())); Rc::<str>::from(std::fs::read_to_string(path).unwrap_or_default()) };
            let v184: i32 = 0;
            let v185: Rc<str> = Rc::<str>::from("let main");
            let v186: i32 = find_from0(v183.clone(), v184, v185.clone());
            let v187: bool = v186 == -1;
            let mut v200: Rc<str>;
            if v187 {
                v200 = v183.clone();
            } else {
                let v188: i32 = line_start1(v183.clone(), v186);
                let v189: i32 = v186 - 1;
                let v190: Rc<str> = SpiralStringSlice(&v183, v188, v189);
                let v191: i32 = (v183).len() as i32;
                let v192: i32 = v191 - 1;
                let v193: Rc<str> = SpiralStringSlice(&v183, v186, v192);
                let v194: i32 = v188 - 1;
                let v195: Rc<str> = SpiralStringSlice(&v183, 0, v194);
                let v196: Rc<str> = SpiralStringConcat(&v195, &v190);
                let v197: Rc<str> = SpiralStringConcat(&v196, &Rc::<str>::from("[<EntryPoint>]\n"));
                let v198: Rc<str> = SpiralStringConcat(&v197, &v190);
                let v199: Rc<str> = SpiralStringConcat(&v198, &v193);
                v200 = v199;
            }
            let v201: i32 = (v200).len() as i32;
            let v202: i32 = trim_at2(v200.clone(), v201);
            let v203: i32 = v202 - 1;
            let v204: Rc<str> = SpiralStringSlice(&v200, 0, v203);
            let v205: i32 = (v204).len() as i32;
            let v206: bool = v205 < 3;
            let mut v215: Rc<str>;
            if v206 {
                v215 = v200.clone();
            } else {
                let v207: i32 = v205 - 3;
                let v208: i32 = v205 - 1;
                let v209: Rc<str> = SpiralStringSlice(&v204, v207, v208);
                let v210: Rc<str> = Rc::<str>::from("\n()");
                let v211: bool = v209 == v210;
                if v211 {
                    let v212: i32 = v205 - 4;
                    let v213: Rc<str> = SpiralStringSlice(&v204, 0, v212);
                    v215 = v213;
                } else {
                    v215 = v200.clone();
                }
            }
            let v217: Rc<str> = Rc::<str>::from(std::path::absolute(v160.as_ref()).unwrap_or_else(|_| std::path::PathBuf::from(v160.as_ref())).display().to_string());
            let v218: i32 = 0;
            let v219: i32 = -1;
            let v220: i32 = last_sep4(v217.clone(), v218, v219);
            let v221: bool = v220 == -1;
            let mut v231: Rc<str>;
            if v221 {
                v231 = v88.clone();
            } else {
                let v222: i32 = v220 - 1;
                let v223: Rc<str> = SpiralStringSlice(&v217, 0, v222);
                let v224: i32 = (v223).len() as i32;
                let v225: bool = v224 == 2;
                let mut v228: bool;
                if v225 {
                    let v226: u8 = SpiralStringIndex(&v223, 1);
                    let v227: bool = v226 == 58;
                    v228 = v227;
                } else {
                    v228 = false;
                }
                if v228 {
                    let v229: Rc<str> = SpiralStringSlice(&v217, 0, v220);
                    v231 = v229;
                } else {
                    v231 = v223.clone();
                }
            }
            let v233: Rc<str> = Rc::<str>::from("dist");
            let v234: Rc<str> = Rc::<str>::from(std::path::Path::new(v231.as_ref()).join(v233.as_ref()).display().to_string());
            let v236: i32 = std::env::args().count() as i32;
            let v237: Rc<str> = Rc::<str>::from("--modules");
            let v238: i32 = 1;
            let v239: i32 = find_flag7(v237.clone(), v238, v236);
            let v240: bool = v239 == -1;
            let mut v244: Rc<str>;
            if v240 {
                v244 = v88.clone();
            } else {
                let v241: i32 = v239 + 1;
                let v242: i32 = 1;
                v244 = module_lines8(v241, v236, v156.clone(), v88.clone(), v242);
            }
            let v246: i32 = std::env::args().count() as i32;
            let v247: Rc<str> = Rc::<str>::from("--packages");
            let v248: i32 = 1;
            let v249: i32 = find_flag7(v247.clone(), v248, v246);
            let v250: bool = v249 == -1;
            let mut v254: Rc<str>;
            if v250 {
                v254 = v88.clone();
            } else {
                let v251: i32 = v249 + 1;
                let v252: i32 = 1;
                v254 = join_args9(v251, v246, v88.clone(), v252);
            }
            let v255: i32 = (v254).len() as i32;
            let v256: bool = v255 == 0;
            let mut v259: Rc<str>;
            if v256 {
                let v257: Rc<str> = Rc::<str>::from("FSharp.Core");
                v259 = v257;
            } else {
                let v258: Rc<str> = SpiralStringConcat(&Rc::<str>::from("FSharp.Core\n"), &v254);
                v259 = v258;
            }
            let v261: Rc<str> = Rc::<str>::from("target");
            let v262: Rc<str> = Rc::<str>::from(std::path::Path::new(v156.as_ref()).join(v261.as_ref()).display().to_string());
            let v264: Rc<str> = Rc::<str>::from("Builder");
            let v265: Rc<str> = Rc::<str>::from(std::path::Path::new(v262.as_ref()).join(v264.as_ref()).display().to_string());
            let v267: Rc<str> = Rc::<str>::from(std::path::Path::new(v265.as_ref()).join(v181.as_ref()).display().to_string());
            let v268: Rc<str> = SpiralStringConcat(&v181, &Rc::<str>::from(".fs"));
            let v270: Rc<str> = Rc::<str>::from(std::path::Path::new(v267.as_ref()).join(v268.as_ref()).display().to_string());
            let v271: Rc<str> = SpiralStringConcat(&v181, &Rc::<str>::from(".fsproj"));
            let v273: Rc<str> = Rc::<str>::from(std::path::Path::new(v267.as_ref()).join(v271.as_ref()).display().to_string());
            let v275: i32 = { let path = std::path::Path::new(v270.as_ref()); i32::from(path.is_file() && std::fs::read_to_string(path).ok().as_deref() == Some(v215.as_ref())) };
            let v276: bool = v275 == 1;
            let mut v300: i32;
            if v276 {
                v300 = 0;
            } else {
                let v277: i32 = 0;
                let v278: i32 = -1;
                let v279: i32 = last_sep4(v270.clone(), v277, v278);
                let v280: bool = v279 == -1;
                let mut v290: Rc<str>;
                if v280 {
                    v290 = v88.clone();
                } else {
                    let v281: i32 = v279 - 1;
                    let v282: Rc<str> = SpiralStringSlice(&v270, 0, v281);
                    let v283: i32 = (v282).len() as i32;
                    let v284: bool = v283 == 2;
                    let mut v287: bool;
                    if v284 {
                        let v285: u8 = SpiralStringIndex(&v282, 1);
                        let v286: bool = v285 == 58;
                        v287 = v286;
                    } else {
                        v287 = false;
                    }
                    if v287 {
                        let v288: Rc<str> = SpiralStringSlice(&v270, 0, v279);
                        v290 = v288;
                    } else {
                        v290 = v282.clone();
                    }
                }
                let v291: i32 = (v290).len() as i32;
                let v292: bool = v291 == 0;
                let mut v295: i32;
                if v292 {
                    v295 = 0;
                } else {
                    let v294: i32 = i32::from(std::fs::create_dir_all(v290.as_ref()).is_err());
                    v295 = v294;
                }
                let v296: bool = v295 == 0;
                if v296 {
                    let v298: i32 = i32::from(std::fs::write(v270.as_ref(), v215.as_ref().as_bytes()).is_err());
                    v300 = v298;
                } else {
                    v300 = v295;
                }
            }
            let v301: Rc<str> = SpiralStringConcat(&Rc::<str>::from("<Project Sdk=\"Microsoft.NET.Sdk\">\n    <PropertyGroup>\n        <TargetFramework>net9.0</TargetFramework>\n        <LangVersion>preview</LangVersion>\n        <RollForward>Major</RollForward>\n        <TargetLatestRuntimePatch>true</TargetLatestRuntimePatch>\n        <ServerGarbageCollection>true</ServerGarbageCollection>\n        <ConcurrentGarbageCollection>true</ConcurrentGarbageCollection>\n        <PublishAot>false</PublishAot>\n        <PublishTrimmed>false</PublishTrimmed>\n        <PublishSingleFile>true</PublishSingleFile>\n        <SelfContained>true</SelfContained>\n        <Version>0.0.1-alpha.1</Version>\n        <OutputType>Exe</OutputType>\n    </PropertyGroup>\n\n    <PropertyGroup Condition=\"$([MSBuild]::IsOSPlatform('FreeBSD'))\">\n        <DefineConstants>_FREEBSD</DefineConstants>\n    </PropertyGroup>\n\n    <PropertyGroup Condition=\"$([MSBuild]::IsOSPlatform('Linux'))\">\n        <DefineConstants>_LINUX</DefineConstants>\n    </PropertyGroup>\n\n    <PropertyGroup Condition=\"$([MSBuild]::IsOSPlatform('OSX'))\">\n        <DefineConstants>_OSX</DefineConstants>\n    </PropertyGroup>\n\n    <PropertyGroup Condition=\"$([MSBuild]::IsOSPlatform('Windows'))\">\n        <DefineConstants>_WINDOWS</DefineConstants>\n    </PropertyGroup>\n\n    <ItemGroup>\n        "), &v244);
            let v302: Rc<str> = SpiralStringConcat(&v301, &Rc::<str>::from("\n        <Compile Include=\""));
            let v303: Rc<str> = SpiralStringConcat(&v302, &v270);
            let v304: Rc<str> = SpiralStringConcat(&v303, &Rc::<str>::from("\" />\n    </ItemGroup>\n    <ItemGroup>\n        <FrameworkReference Include=\"Microsoft.AspNetCore.App\" />\n    </ItemGroup>\n    <Import Project=\""));
            let v305: Rc<str> = SpiralStringConcat(&v304, &v156);
            let v306: Rc<str> = SpiralStringConcat(&v305, &Rc::<str>::from("/.paket/Paket.Restore.targets\" />\n</Project>\n"));
            let v308: i32 = { let path = std::path::Path::new(v273.as_ref()); i32::from(path.is_file() && std::fs::read_to_string(path).ok().as_deref() == Some(v306.as_ref())) };
            let v309: bool = v308 == 1;
            let mut v333: i32;
            if v309 {
                v333 = 0;
            } else {
                let v310: i32 = 0;
                let v311: i32 = -1;
                let v312: i32 = last_sep4(v273.clone(), v310, v311);
                let v313: bool = v312 == -1;
                let mut v323: Rc<str>;
                if v313 {
                    v323 = v88.clone();
                } else {
                    let v314: i32 = v312 - 1;
                    let v315: Rc<str> = SpiralStringSlice(&v273, 0, v314);
                    let v316: i32 = (v315).len() as i32;
                    let v317: bool = v316 == 2;
                    let mut v320: bool;
                    if v317 {
                        let v318: u8 = SpiralStringIndex(&v315, 1);
                        let v319: bool = v318 == 58;
                        v320 = v319;
                    } else {
                        v320 = false;
                    }
                    if v320 {
                        let v321: Rc<str> = SpiralStringSlice(&v273, 0, v312);
                        v323 = v321;
                    } else {
                        v323 = v315.clone();
                    }
                }
                let v324: i32 = (v323).len() as i32;
                let v325: bool = v324 == 0;
                let mut v328: i32;
                if v325 {
                    v328 = 0;
                } else {
                    let v327: i32 = i32::from(std::fs::create_dir_all(v323.as_ref()).is_err());
                    v328 = v327;
                }
                let v329: bool = v328 == 0;
                if v329 {
                    let v331: i32 = i32::from(std::fs::write(v273.as_ref(), v306.as_ref().as_bytes()).is_err());
                    v333 = v331;
                } else {
                    v333 = v328;
                }
            }
            let v335: Rc<str> = Rc::<str>::from("paket.references");
            let v336: Rc<str> = Rc::<str>::from(std::path::Path::new(v267.as_ref()).join(v335.as_ref()).display().to_string());
            let v338: i32 = { let path = std::path::Path::new(v336.as_ref()); i32::from(path.is_file() && std::fs::read_to_string(path).ok().as_deref() == Some(v259.as_ref())) };
            let v339: bool = v338 == 1;
            let mut v363: i32;
            if v339 {
                v363 = 0;
            } else {
                let v340: i32 = 0;
                let v341: i32 = -1;
                let v342: i32 = last_sep4(v336.clone(), v340, v341);
                let v343: bool = v342 == -1;
                let mut v353: Rc<str>;
                if v343 {
                    v353 = v88.clone();
                } else {
                    let v344: i32 = v342 - 1;
                    let v345: Rc<str> = SpiralStringSlice(&v336, 0, v344);
                    let v346: i32 = (v345).len() as i32;
                    let v347: bool = v346 == 2;
                    let mut v350: bool;
                    if v347 {
                        let v348: u8 = SpiralStringIndex(&v345, 1);
                        let v349: bool = v348 == 58;
                        v350 = v349;
                    } else {
                        v350 = false;
                    }
                    if v350 {
                        let v351: Rc<str> = SpiralStringSlice(&v336, 0, v342);
                        v353 = v351;
                    } else {
                        v353 = v345.clone();
                    }
                }
                let v354: i32 = (v353).len() as i32;
                let v355: bool = v354 == 0;
                let mut v358: i32;
                if v355 {
                    v358 = 0;
                } else {
                    let v357: i32 = i32::from(std::fs::create_dir_all(v353.as_ref()).is_err());
                    v358 = v357;
                }
                let v359: bool = v358 == 0;
                if v359 {
                    let v361: i32 = i32::from(std::fs::write(v336.as_ref(), v259.as_ref().as_bytes()).is_err());
                    v363 = v361;
                } else {
                    v363 = v358;
                }
            }
            let v364: Rc<str> = Rc::<str>::from("--persist-only");
            let v365: i32 = 1;
            let v367: i32 = std::env::args().count() as i32;
            let v368: i32 = find_flag7(v364.clone(), v365, v367);
            let v369: bool = v368 == -1;
            let mut v370: i32;
            if v369 {
                v370 = 0;
            } else {
                v370 = 1;
            }
            let v371: bool = v370 == 1;
            if v371 {
                return 0;
            } else {
                let v372: Tuple9001 = TupleCreate9001(0, v273.clone(), v234.clone());
                let v374: i32 = std::env::args().count() as i32;
                let v375: Rc<str> = Rc::<str>::from("--runtime");
                let v376: i32 = 1;
                let v377: i32 = find_flag7(v375.clone(), v376, v374);
                let v378: bool = v377 == -1;
                let mut v393: Rc<str>;
                if v378 {
                    v393 = v88.clone();
                } else {
                    let v379: i32 = v377 + 1;
                    let v380: bool = v379 == v374;
                    if v380 {
                        v393 = v88.clone();
                    } else {
                        let v382: Rc<str> = Rc::<str>::from(std::env::args().nth(v379 as usize).unwrap_or_default());
                        let v383: i32 = (v382).len() as i32;
                        let v384: bool = v383 < 2;
                        let mut v388: bool;
                        if v384 {
                            v388 = false;
                        } else {
                            let v385: Rc<str> = SpiralStringSlice(&v382, 0, 1);
                            let v386: Rc<str> = Rc::<str>::from("--");
                            let v387: bool = v385 == v386;
                            v388 = v387;
                        }
                        if v388 {
                            v393 = v88.clone();
                        } else {
                            let v390: Rc<str> = Rc::<str>::from(std::env::args().nth(v379 as usize).unwrap_or_default());
                            v393 = v390;
                        }
                    }
                }
                let v394: i32 = (v393).len() as i32;
                let v395: bool = v394 == 0;
                let mut v398: Tuple9002;
                if v395 {
                    v398 = TupleCreate9002(1, Rc::<str>::from(""), 0);
                } else {
                    v398 = TupleCreate9002(0, v393.clone(), 0);
                }
                return publish10(v372, v398);
            }
        } else {
            std::process::abort();
        }
    }
}

fn main() {
    std::process::exit(spiral_main());
}


